### ISSUE TITLE
Default workspace to a temp directory

### ISSUE THREAD

**Issue by neoziro** [shipitjs/shipit#10]

**Comment by halfdan** [comment]
Can you explain what you mean here?

**Comment by neoziro** [comment]
I mean that workspace should default to a temp directory automatically created using tmp module.

**Comment by grEvenX** [comment]
:+1:

**Comment by neoziro** [comment]
Will be part of v4 https://github.com/shipitjs/shipit/issues/148#issuecomment-341193086
