### ISSUE TITLE
Destination with space isn't escaped properly

### ISSUE THREAD

**Issue by sjelfull** [shipitjs/shipit#100]
*I'm copying my issue over from shipitjs/ssh-pool#13*

I'm trying to copy a file from remote to locally, and my destination path has spaces in it. This causes rsync to freak out and return an error.

This is my test task in shipit:

```javascript
shipit.task('testspace', function () {
    return shipit.remoteCopy('/home/test/path/file.bz2', '/Users/fred/Projects/Path With Space/', {
      direction: 'remoteToLocal'
    });
});
```

This is the error returned by rsync:
```
rsync error: syntax or usage error (code 1) at /SourceCache/rsync/rsync-45/rsync/main.c(1166) [receiver=2.6.9]

    at ChildProcess.exithandler (child_process.js:696:12)
    at ChildProcess.EventEmitter.emit (events.js:104:17)
    at maybeClose (child_process.js:808:16)
    at Socket.<anonymous> (child_process.js:1025:11)
    at Socket.EventEmitter.emit (events.js:101:17)
    at Pipe.close (net.js:459:12)
```

Without spaces, it works just fine. I also tried to escape it manually:

`/Users/fred/Projects/Path\ With\ Space/`

I can take a crack at normalizing the path and send a pull request when time allows?

**Comment by neoziro** [comment]
I am not sure that writing a path without escaping spaces is valid, I think we must not escape paths.

```js
$ cd /Library/PDF Services
cd: string not in pwd: /Library/PDF
```

**Comment by sjelfull** [comment]
I think there is something to be said for developer expectations, right? 

Do you have any problem with normalizing paths? If we do that, then it doesn't matter if they have spaces or not in them.

**Comment by neoziro** [comment]
@sjelfull yes I think it's a problem because it's not the role of Shipit to normalize paths.
