### ISSUE TITLE
'rsync' fails completely when remote doesn't have it installed.

### ISSUE THREAD

**Issue by mgebundy** [shipitjs/shipit#101]
I'm currently working with many smaller embedded systems and would like to deploy with ShipIt or another nodejs based deployment system.

Unfortunately I noticed the complete dismissal of supporting something other than `rsync` in #20, since there are more issues with rsync than just Windows

If a remote device doesn't have rsync installed, it fails completely. `ssh-pool` only checks if it's installed on local, not remote, and there's no way to override and force `scp` usage.

A solution to this would be incredibly useful. Thank you!

**Comment by neoziro** [comment]
@mgebundy I understand but to keep it simple I choose to only implement rsync. What kind of issues do you experience with rsync, I am curious.

**Comment by travco** [comment]
Known behavior, not on track have a fix implemented. 

If I'm not mistaken the mentality is that if rsync can be installed, it should, as the package is (at worst) 113.0 kB. If it can't, to support it would be opening a near-endless pandora's box of proprietary, or depreciated methods on closed embedded systems - which isn't in the scope of the repo, as the configuration to get shipit working (on all of the things!) would be equally complex as making a shell script (or npm script) to do the same thing.

@timkelty Stagnant issue, suggest closing?

**Comment by timkelty** [comment]
As of now, Shipit requires rsync, however PRs are always welcome.
