### ISSUE TITLE
Restarting node service using shipit

### ISSUE THREAD

**Issue by Loupax** [shipitjs/shipit#103]
I am having the following shipit.js file which I use to deploy my app, and restart it once everything is complete:

```
module.exports = function(shipit){
	require('shipit-deploy')(shipit);
    require('shipit-npm')(shipit);

  shipit.initConfig({
    'default':{
      workspace: '/tmp/app',
      repositoryUrl: 'ssh://git@git.com/app.git',
      branch: 'master',
      ignores: ['.git', 'node_modules'],
      rsync: ['--del'],
      keepReleases: 2,
      shallowClone: true,
      deployTo:'/home/deploy/app/httpdocs',
    },
    'server1':{
      restart: 'sudo systemctl restart app.service',
      servers: 'deployer@server1'
    },
    'server2': {
      restart: 'sudo service app restart',
      servers: 'deployer@server2'
    }
  });

  shipit.task('restart', function(){
      return shipit.remote(shipit.config.restart);
  });

};
```

You will notice that each server has a different command that restarts the service since one is using `systemv` and the other uses `upstart` to manage services

Running `shipit server2 restart` works fine, but running `shipit server1 restart` asks my for my password and then stays there doing nothing and I can only leave there by Ctrl+break. Has anyone encountered this thing? Am I doing something wrong?

**Comment by neoziro** [comment]
@Loupax normally sudo will give you an interactive mode. But I advice you to give correct rights to your shipit user on that file to avoid using sudo.

**Comment by Loupax** [comment]
Tried to do the same thing without using shipit just by doing `ssh server sudo restart_my_server` and received a `sudo: sorry, you must have a tty to run sudo` error that was not visible when using shipit. 

Maybe there is something about the way errors get handled that causes the error not to appear?

**Comment by travco** [comment]
Hey @Loupax, if this sorted out everything for you would you mind closing the issue?

Otherwise feel free to reply! (though that would suck if you still didn't have this working)

**Comment by Loupax** [comment]
Haven't solved this issue with sudo, but I think we should close it anyway
