### ISSUE TITLE
Add license correctly

### ISSUE THREAD

**Issue by rugk** [shipitjs/shipit#104]
You indicate you want to [license this under a MIT license](https://github.com/shipitjs/shipit#license). However this does not work by just adding three words. 

You have to add [the full wording](http://choosealicense.com/licenses/mit/) of the license. Usually this is added to a file `LICENSE` or `LICENSE.txt/.md`. Additionally you may add a small notice as a comment to all source files in this repo or even add the full license as a comment there too.

**Comment by iDuuck** [comment]
Just made a pr for adding this.
