### ISSUE TITLE
Funny smiley

### ISSUE THREAD

**Issue by rugk** [shipitjs/shipit#105]
FYI I found this repo by searching for the smiley :shipit:  - it's `:shipit:`.

If you want to make a small joke in this repo/project here you may add this icon somewhere. :smiley:

**Comment by travco** [comment]
@rugk The shipit squirrel has more to do with a development mindset than this repo: https://www.quora.com/GitHub-What-is-the-significance-of-the-Ship-It-squirrel
Suggestion noted, and appreciated.

@timkelty I think this issue fufilled it's "purpose" of telling the shipit team that there is an Emoji of the same name, probably can be closed.

**Comment by timkelty** [comment]
:shipit::shipit::shipit::shipit::shipit::shipit::shipit::shipit:
