### ISSUE TITLE
Shouldn't a the dependencies of a blocking task also block?

### ISSUE THREAD

**Issue by weotch** [shipitjs/shipit#107]
My use case is that during a shipit-deploy, after the git merge, I want to install npm dependencies in a couple directories and then build using webpack.  The npm installs can happen in parallel.  So this is my config:

```js
shipit.on('fetched', function() {
  return shipit.start('compile');
});

shipit.blTask('compile', ['install tools', 'install public'], function() {
  return shipit.local('webpack -p', {
    cwd: shipit.config.workspace
  });
});

shipit.task('install tools', function() {
  return shipit.local('npm install', {
    cwd: shipit.config.workspace
  });
});

shipit.task('install public', function() {
  return shipit.local("npm --prefix ./resources/assets install ./resources/assets", {
    cwd: shipit.config.workspace
  });
});
```

My expectation is that because the `compile` task is blocking, the dependent tasks will also hold up shipit from moving on to `deploy:update` and that the `install` tasks will run in parallel.  What I'm seeing happening is that the `compile` task is waiting for the two `install` tasks to complete, but it's not holding up the deploy.  Here's the relevant section of the output:

```txt
Branch merged.
Finished 'deploy:fetch' after 2.99 s

Running 'install tools' task...
Running "npm install" on local.

Running 'install public' task...
Running "npm --prefix resources/assets install resources/assets" on local.

Running 'deploy:update' task...
```

Is this working as intended?  If so, do you have a recommendation for getting the behavior I'm looking for?  Thanks!

**Comment by kwoon** [comment]
Try all you tasks create via blTask

**Comment by neoziro** [comment]
Good question, but just use blTask for everything and it would work fine.
