### ISSUE TITLE
Unable to find remote helper for 'git+https'

### ISSUE THREAD

**Issue by vroudge** [shipitjs/shipit#108]
Hello,

I keep on getting this error whenever I try to deploy using Shipit. I've tried pretty much everything I can, I'm really desperate. Anyone ever had this error? 

Best,
Valentin

**Comment by neoziro** [comment]
Should be good since we use git command line, maybe it's a problem relative to your git installation.

**Comment by travco** [comment]
Hey @vroudge, are you still having problems with this? If so, if you could post a bit more context for the error that would be helpful.

Otherwise if you could close the issue it would be appreciated!
