### ISSUE TITLE
Document alternative shipitfile.js command line argument

### ISSUE THREAD

**Issue by Tomtomgo** [shipitjs/shipit#109]
The cli program `shipit` [accepts a 'shipitfile' parameter](https://github.com/shipitjs/shipit/blob/73dbc757e3dff01fe3c2eedfb7bdd7a59185b0f1/bin/shipit#L21). I could not find this in the documentation. Useful option to add to the docs!

**Comment by neoziro** [comment]
This is handled by Liftoff so you can refer to Liftoff documentation if you want to know every options. I think it's very advanced and I didn't mention it in documentation.
