### ISSUE TITLE
Default to shallowClone

### ISSUE THREAD

**Issue by neoziro** [shipitjs/shipit#11]

**Comment by neoziro** [comment]
This will not be done, it's great to be able to keep a cache of the latest build, and with the normal mode, it's easier to do.

**Comment by thelinuxlich** [comment]
which is faster?

**Comment by neoziro** [comment]
@thelinuxlich depends your need, personally I don't use shallowClone, I use a local directory as workspace, so I don't have to re-install node_modules at each deployment.
