### ISSUE TITLE
run ShipIt as user from command line

### ISSUE THREAD

**Issue by jwerre** [shipitjs/shipit#110]
It would be nice if you could run a SHIPIT command as a user from the command line so you don't have to add it to `shipitfile` Something like this:

    shipit --user <server_username> staging pwd

This way multiple users could use the same `shipitfile`. 

Currently I'm adding these lines to `shipitfile`, which seems to work but it's kind of hacky:

	file = "/etc/deploy.conf"
	try {
		config = JSON.parse( fs.readFileSync(file, "utf8") )
	} catch (e) {
		throw new Error("Invalid Config: Ensure "+file+" exists and the JSON is valid."+ e.toString())
	}

	console.log(config.user); // bill

	module.exports = function (shipit) {

		shipit.initConfig({

			staging: {
				servers: config.user+'@my-staging-server.com'
			},

		});

		shipit.task('pwd', function () {
			return shipit.remote('pwd');
		});
	};

**Comment by neoziro** [comment]
Since the shipitfile.js is dynamic, you can customize user in config as you want. You can use minimist to extract arguments, or you can use environment variables, that why it's no built in shipit.
