### ISSUE TITLE
GIT_WORK_TREE error

### ISSUE THREAD

**Issue by thelinuxlich** [shipitjs/shipit#111]
Getting this error when deploying:

```
Error: Command failed: /bin/sh -c git init
fatal: GIT_WORK_TREE (or --work-tree=<directory>) not allowed without specifying GIT_DIR (or --git-dir=<directory>)
```

**Comment by thelinuxlich** [comment]
Downgrading my git executable to 2.5 fixes this issue. Probably something changed on 2.7

**Comment by neoziro** [comment]
Hmm probably.. But is it relative to Shipit?

**Comment by travco** [comment]
Hey @thelinuxlich, if this is resolved for you would you mind closing the issue?
