### ISSUE TITLE
Running a command as a specific user and bootstrapping a new server

### ISSUE THREAD

**Issue by vjpr** [shipitjs/shipit#112]
What is the general approach to bootstrap a server, i.e. setup the `deploy` user?

I'd like to be able to run `init:remote` with shipit to setup the server and ssh access, after a create a new DigitalOcean droplet or an AWS EC2 instance.

I initially tried `shipit.remote(..., {user: 'root'})`

Or do I have to use something like Ansible?

**Comment by neoziro** [comment]
Yes you should, Shipit is designed to run basic commands and deploy code, it's not designed to manage pool of servers.
