### ISSUE TITLE
Access current host/server when deploying multiple servers

### ISSUE THREAD

**Issue by danielsarin** [shipitjs/shipit#113]
Hi,

I'm using shipit to deploy to multiple servers in batches. I would like to deploy all servers with just a single command, but some of the servers require custom run configurations.

If I deploy them one at a time, I can add a custom parameter to the object, for example

    test: {
      servers: ['user@test.example.com'],
      branch: 'test',
      deployTo: '/home/vuo/vuoacademic',
      runConfig: 'ENV_VAR=asd'
    }

Then run `shipit test deploy` and then access that variable when running a task from `shipit.config.runConfig`. But we have many servers and updating them one by one would take a lot of time.

I know I can add multiple servers like this

    clients: {
      servers: [
        'user@client1.example.com',
        'user@client2.example.com',
        'user@client3.example.com'
      ],
      branch: 'test',
      deployTo: '/home/vuo/vuoacademic',
      runConfig: 'ENV_VAR=asd'
    }

But now `runConfig` is the same for all servers.

I was thinking I could define the run configs in a separate object, and then access the value based on the host. But I don't know how to access the host, it's not part of the `Sequelize` object. I.e. when executing a task I would like to know the current host, ex. `client2.example.com`.

Is this even possible? Any other suggestions on how to tackle this problem?

**Comment by mattanglin** [comment]
@danielsarin As far as I know you can add custom config for each of your servers in the servers array like so:
```
servers: [
  {
    user: "user",
    host: "client1.example.com",
    runConfig: "ENV_VAR=asd1"
  },
  {
    user: "user",
    host: "client2.example.com",
    runConfig: "ENV_VAR=asd2"
  },
  {
    user: "user",
    host: "client3.example.com",
    runConfig: "ENV_VAR=asd3"
  }
],
```

Then you can access the runConfig variable for each server at the runConfig key for that server:

```
shipit.task('sometask',function() {
  for (var i=0, l = shipit.config.servers.length; i<l;i++) {
    var serverConfig = shipit.config.servers[i];
    console.log(serverConfig.runConfig);
  }
});
```

**Comment by danielsarin** [comment]
I'm not sure if I was clear, but if I'm deploying server 1 and 2, and they both execute that task, then for each execution I would need to access that specific servers runConfig.

**Comment by neoziro** [comment]
@danielsarin it's not a good practice to have different configuration on the same group of server.. That's why it's not built in Shipit. I think you can find a workaround to your specific case by doing two commands (first reading the server, second executing the command?). You can also put a script on each server to accomplish the task you need on the different server. For more flexibility, you should take a look to chef or others tools like this.

**Comment by gernovich** [comment]
1.
`    var remoteWithCondition = function(command, options, condition) {
        return Promise.all(shipit.pool.connections.map(function(connection) {
            if(condition(connection.options.remote)) {
                return connection.run(command, options);
            }
        }));
    };
`

2. 
`servers: [
  {
    user: "user",
    host: "client1.example.com",
    is_front: true
  },
  {
    user: "user",
    host: "client2.example.com",
    is_front: true
  },
  {
    user: "user",
    host: "client3.example.com",
    is_front: false
  }
],`

3.
`    shipit.blTask('remote:nginx', function () {
        return remoteWithCondition('sudo service nginx reload', [], function (remote) {
            return remote.is_front;
        })
    });`
