### ISSUE TITLE
Error: EACCES, mkdir '/var/www' on CentOS

### ISSUE THREAD

**Issue by Truemedia** [shipitjs/shipit#114]
Hi,
I have managed to setup shipit for deploying to a remote server using the coding sample from the README file, but when I change the workspace or deployTo parameters to the directory I want which is /var/www/mywebsite.com I get the following error:

Running 'deploy:init' task...
Finished 'deploy:init' after 1.38 ms

Running 'deploy:fetch' task...
Deleting existing workspace "/var/www/mywebsite.com"
Running "rm -rf /var/www/mywebsite.com" on local.
Create workspace "/var/www/mywebsite.com"
'deploy:fetch' errored after 25 ms
Error: EACCES, mkdir '/var/www'

Iv'e run a recursive chown for my deploy user on that directory as some people suggested, but I still get the same issue. Any advice on how to fix the issue? I figure this may be a common problem.

**Comment by travco** [comment]
Hey @Truemedia, if you could run `ls -altc` in that workspace and post the result that would be helpful.

I have a suspension this is more of a Linux permissions ordeal than anything to do with Shipit, but I'm happy to help.

**Comment by Truemedia** [comment]
@travco Hi Trav,
Sorry forgot to update this I actually managed to fix this from what I remember, I think it was just a case of a file that was stubborn with permissions inside the repo.
 
If I have the same issue again I will reference this issue, thanks.

**Comment by travco** [comment]
@Truemedia Well, glad to hear it's gone.

Would you mind closing the issue then?

**Comment by Truemedia** [comment]
Yep sorry, closing.
