### ISSUE TITLE
Remote command is not using correct environment variables

### ISSUE THREAD

**Issue by sean-roberts** [shipitjs/shipit#117]
So this might be a permissions thing, but I have a feeling it's not. My situation is that I am running the script below and it seems as if it correctly executing on the remote but the configuration is pointing at the local.

```javascript
module.exports = function (shipit) {
  require('shipit-deploy')(shipit);

  shipit.initConfig({
    default: {
      workspace: 'shipit-workspace/',
      deployTo: '/var/services/site-mappings/',
      repositoryUrl: '...giturl...',
      ignores: ['.git', 'node_modules'],
      rsync: ['--del'],
      keepReleases: 2,
      shallowClone: true
    },
    production: {
      servers: 'deployer@xxx.xxx.xx.xxx'
    }
  });

  shipit.blTask('install',function(){
    var path = shipit.releasePath;
    return shipit.remote('echo $PATH && cd ' + path + ' && npm install && npm ls -depth 0');
  });

  shipit.on('published', function(){
     return shipit.start(['install']);
  });
};
```

The issue is in the install blTask. npm is not available. Adding the echo of $PATH it prints
`/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin` which is what is on my local -- **not on the remote**.
When I ssh into the remote as deployer and print my $PATH it is completely different and thus npm is not being found.

Output of the above mentioned error:

```
Running "echo $PATH && cd /var/services/site-mappings/releases/20160317014433 && npm install && npm ls -depth 0" on host "xxx.xxx.xx.xxx".

@xxx.xxx.xx.xxx /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/local/bin:/opt/local/sbin
@xxx.xxx.xx.xxx-err bash: npm: command not found
'install' errored after 1.15 s
Error: Command failed: bash: npm: command not found

    at ChildProcess.exithandler (child_process.js:647:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:753:16)
    at Socket.<anonymous> (child_process.js:966:11)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Pipe.close (net.js:465:12)
```

I feel like I am going crazy here perhaps you can point me in a direction that can get this going?
Let me know if there is any more info I can give.

**Comment by sean-roberts** [comment]
Damnit... -_- 

I was rocking a .bashrc file and added nvm. What I just learned the hard way, .bashrc usually comes with a snippet that will stop execution of the bash script at a certain point if it is a non interactive shell. Thus, with nvm appending it's script to the bottom of the file, it was never getting to the point where it initialized nvm then getting npm available - more or less.

Hope that helps anyone who finds themselves in a similar situation.

**Comment by jasonpang** [comment]
@sean-roberts 

Thanks so much for this tip! I wasn't understanding why environment variables set in `~/.bashrc` weren't being set in my program. As you mentioned, the top of the `~/.bashrc` file contains a snippet that returns if not running interactively.

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

**Comment by erwin16** [comment]
thanks for the tip ! +1
