### ISSUE TITLE
remoteCopy doesn't respect rsync flags from opts if config.rsync is set

### ISSUE THREAD

**Issue by flyingrobots** [shipitjs/shipit#119]
https://github.com/shipitjs/shipit/blob/master/lib/shipit.js#L246

In `remoteCopy`, `this.config.rsync` will always be used, if it is specified. `options.rsync` is ignored.

Why should we obey `this.config` over the `opts` arguments that are passed in? Expected behavior is to be able to override rsync behavior when we need to by using the `options` argument.

Not only that, but it looks like, according to https://lodash.com/docs#assign, `_.assign` will copy properties from the `sources` from left to right. So if I understand that correctly, we copy all properties from `options`, then override `rsync` and `ignores` with a value from `this.config` or (redundantly) `options` if `this.config.rsync` is undefined... So, it seems like the order here should be swapped so that `rsync` is copied from `this.config` first, and `options` last, which would allow you to actually override the `rsync` behavior when you want to.

I can get a PR with this change if there is consensus that this is indeed a bug. Maybe I'm just missing something? I git blamed this line and there is a commit that implies that this is actually what the desired behavior is... but that seems completely broken, because now we have no way to override the `rsync` flags for special cases. 0ec98e80a793caab9664d00faae9aa30f46298a1

@mochja Seems like you touched this last. Looks like `_.defaults` doesn't override stuff, but `_.assign` behaves differently. So actually your change seems to break this, or at least your change now causes behavior that breaks my expectations as a user.

**Comment by my-digital-decay** [comment]
#84

**Comment by mochja** [comment]
@flyingrobots yes from this point of view, it should override the global config.

I was looking at this from end user perspective and I think I wanted to [replace `--del` option from the default behaviour](https://github.com/shipitjs/shipit-deploy/blob/bdf0c4cd70dbff52a6bdcbf73d492786a8b81e30/tasks/deploy/update.js#L71) and [add few more.](https://github.com/shipitjs/shipit-deploy/pull/76).

Maybe it would be better to set the `{rsync: '--del'}` as [default config](https://github.com/shipitjs/shipit/blob/ff01ebe7df16592b87477b050e27c2aafbb0a289/lib/shipit.js#L160) and [remove explicitly passed option](https://github.com/shipitjs/shipit-deploy/blob/bdf0c4cd70dbff52a6bdcbf73d492786a8b81e30/tasks/deploy/update.js#L71), override globals with the passed options and after that it would behave as it should from both sides, am I right ?

**Comment by flyingrobots** [comment]
Yeah so I don't really grasp what you're trying to say.

I don't think it's OK to impose defaults to the behavior of rsync that aren't part of the default behavior of rsync. You have to explicitly tell rsync to delete things with `--del`, so why should this be the default behavior of shipit?

I do think it's OK to respect that's in the config, or what has been passed to `options`. And that in general an API should always choose the most "locally defined" overrides (in this case the `options` argument).

If I understand you, you made this change to shipit because of a use case in an unrelated project (shipit-deploy), and you're trying to think out loud with me about how to factor your changes to that project in such a way that we can restore the expected functionality to shipit...

Ultimately, the API for shipit should not be changed just because of a use case in another, unrelated project. Especially not when your changes to shipit break the intuitive use case of its API.

**Comment by my-digital-decay** [comment]
I would recommend reverting the changes in 'shipit' to return the old behavior (argument parameters override config settings) and implement your requirements in shipit-deploy. You could merge together the config values and argument values in shipit-deploy's remoteCopy function and pass the resulting configuration down trough the the opts param into shipit.

**Comment by mochja** [comment]
Yes, this change was done because of shipit-deploy project, which options for rsync couldn't be overridden (`{rsync: '--del'}`).

----

Simply I just wanted to change rsync parameters for deploy command as shown in [example](https://github.com/shipitjs/shipit/blob/3d2e16552adc03bd0e4f983b4793aca060bd6218/README.md#example-shipitfilejs), but that didn't work. I got confused why, so I dig into the code, "fixed" it for me and submitted the PR for a review.

@grEvenX also pointed this API problem, but after a while my PR got merged.

I'm sorry, I don't know the ecosystem of shipit.

Now, I can say that change should be done in shipit-deploy package, instead of here. ([as I originally indented](https://github.com/shipitjs/shipit-deploy/pull/76))

**Comment by flyingrobots** [comment]
@mochja can you fix this please? This is very frustrating because there is no way to override rsync flags per-command using shipit. Please fix ASAP - this is critical.

**Comment by timkelty** [comment]
@flyingrobots I'll try and look into to tomorrow.

**Comment by timkelty** [comment]
Seems like this would be fixed by using `_.defaults` (as it originally was) instead of `_.assign`.

@mochja Do you recall why you changed it to `_.assign`?

**Comment by flyingrobots** [comment]
@timkelty yes please

**Comment by ember-graab** [comment]
Here's a pull request to fix this issue:
https://github.com/shipitjs/shipit/pull/127

**Comment by flyingrobots** [comment]
Looks like the PR is failing because the tests were changed when @mochja broke stuff 😫

**Comment by timkelty** [comment]
Were you all installing this straight from `master`? Just realized that the latest NPM release was `1.4.1`, which didn't have the original PR merged in yet.

Regardless, it has been reverted in master: https://github.com/shipitjs/shipit/commit/e54af19d90d6b1ae68fbea28eeb6c52b6fa3f5a1

Since it was never published to NPM, I don't think we need a new version published, but let me know if I'm wrong.

**Comment by timkelty** [comment]
@mochja Please check out shipitjs/shipit-deploy#master in conjunction with shipitjs/shipit#master

You can now set `remoteCopy: {rsync: '--foo'}` in your shipit config to override the option passing when deploying.

If that works for you I'll publish a new version.

**Comment by timkelty** [comment]
Would like to publish new versions of both shipit-cli and shipit-deploy.
Can someone on this thread make sure my additions meet your needs before I do?

**Comment by travco** [comment]
Hey @flyingrobots,
Any chance you could check if everything you needed is sorted out on your end?
