### ISSUE TITLE
Make TTY optional

### ISSUE THREAD

**Issue by neoziro** [shipitjs/shipit#12]

**Comment by IcanDivideBy0** [comment]
+1

**Comment by neoziro** [comment]
Will be done soon https://github.com/shipitjs/ssh-pool/pull/26

**Comment by neoziro** [comment]
Will be done in v4 #156

**Comment by neoziro** [comment]
https://github.com/shipitjs/shipit/tree/master/packages/ssh-pool#connectionruncommand-options

```js
shipit.remote('ls', { tty: true })
```
