### ISSUE TITLE
no connection to remote server possible

### ISSUE THREAD

**Issue by ludwigmair** [shipitjs/shipit#123]
Hi, 
i am just exploring shipit and i am not able to connect to the remote server.
here my error
`Running 'pwd' task...
Running "pwd" on host "mydomain.de".
a29558zx@mydomain.de's password:
a29558zx@mydomain.de's password: @mydomain.de-err Permission denied, please try again.`

my config
`module.exports = function (shipit) {
  require('shipit-deploy')(shipit);
  shipit.initConfig({
    default: {
      workspace: '/Users/ludwigmair/www/mydomain.dev/typo3conf/ext/triamembers/deploy-workspace',
      deployTo: 'mydomain.de/www.xxx/deploy',
      repositoryUrl: 'git@gitlab.com:myname/myrepo.git',
      ignores: ['.git', 'node_modules'],
      keepReleases: 3,
      key: '~/.ssh/id_rsa.pub',
      branch : 'master',
      shallowClone: true,
      deleteOnRollback: false,
    },
live: {
        servers: 'a29558xx@mydomain.de',
        keepReleases: 3,
        deployTo: 'mydomain/live', 
        branch : 'master',
    }

  });
shipit.on('updated', function () {
    var buildDirectory = path.resolve('./live/');
    shipit.remoteCopy(buildDirectory, shipit.releasePath);
  });
};`

i appreciate any help

thanks 
Ludwig

**Comment by travco** [comment]
That's a pretty default remote terminal error for not having proper credentials.

Have you double-checked that the password your passing along is correct?
Also, by the looks of your config you've set the ssh key, have you configured your server to accept ssh keys and told it to trust yours?

**Comment by ludwigmair** [comment]
yes , i have
