### ISSUE TITLE
Multiple environments and using pm2

### ISSUE THREAD

**Issue by jdnichollsc** [shipitjs/shipit#124]
Hi guys,

Exist any example with multiple environments and using pm2 to restart the service?

I'm using Amazon instances and for the moment using MobaXterm via SSH to deploy the code manually, but I would love use this to deploy the code using a script

Thanks in advance, Nicholls

**Comment by timkelty** [comment]
I think my coworker has done this on a project. I'll check with him tomorrow and get back to you.

**Comment by jdnichollsc** [comment]
Woww, amazing! Thanks for your help :dancers:

**Comment by mattanglin** [comment]
@jdnichollsc I've been using shipit and PM2 in production on multiple environments and wrote a simple little shipit plugin for my needs. It's little incomplete currently, but may be a good starting point.

[https://github.com/mattanglin/shipit-pm2-nginx](https://github.com/mattanglin/shipit-pm2-nginx)

**Comment by jdnichollsc** [comment]
Hi @mattanglin,

Is possible to configure some environments (with differents settings for each one) and later select which one will deploy the code?

PD: Sorry for my bad English haha

Thanks in advance, Nicholls

**Comment by mattanglin** [comment]
Hi @jdnichollsc,

The PM2 part of the plugin uses [PM2 Application Declaration files](http://pm2.keymetrics.io/docs/usage/application-declaration/) for controlling starting/stopping of the application within PM2. When you first setup your application you'll need to run the [pm2:generate](https://github.com/mattanglin/shipit-pm2-nginx#pm2--nginx-configuration) task for each environment to create this config on your servers. You can set any number of different environment configurations for PM2 like so:

```
shipit.initConfig({
    default: {
      name: 'example-app',
      pm2: {
        conf: {
          watch: true,
          script: 'bin/www'
        }
      },
    },

    environment1: {
      pm2: {
        pm2setting: 'some environment1 value',
      },
      port: 8001
    },
    environment2: {
      pm2: {
        pm2setting: 'some environment2 value',
      }
    },
    port: 8080
  });
```

Then generate the PM2 configurations for each environment:
```
$ shipit environment1 pm2:generate
$ shipit environment2 pm2:generate
```

When you deploy to an environment the plugin will automatically restart your application according to the PM2 config. You can also manually run the tasks for each environment:

```
$ shipit envionment1 pm2:restart
$ shipit envionment2 pm2:restart
```

**Comment by jdnichollsc** [comment]
Very Cool @mattanglin! :100: 

Is possible to define a SSH key and deployTo different per environment?

Thanks in advance

**Comment by mattanglin** [comment]
As far as I know you can very easily set the deployTo for each environment in their respective shipit configurations.
As for defining SSH keys I would do this manually per server and not from within shipit as it's a one time thing. That being said you can specify your user not just per environment, but on an individual server basis within your server config if you need that much granularity:

```
shipit.initConfig({
  ...

  environ1: {
    deployTo: '/environ1/deploy/path',
    servers: [
      {
        host: 0.0.0.1,
        user: 'deployfor0001',
      },
      {
        host: 0.0.0.2,
        user: 'deployfor0002',
      }
    ]
  },
  environ2: {
    deployTo: '/environ2/deploy/path',
    servers: [
      {
        host: 0.0.0.1,
        user: 'env2deployfor0001',
      },
      {
        host: 0.0.0.2,
        user: 'env2deployfor0002',
      }
    ]
  }
})
```

**Comment by travco** [comment]
If this worked out for you @jdnichollsc, would you mind closing your issue?

**Comment by jdnichollsc** [comment]
yes, thanks guys! :dancers:
