### ISSUE TITLE
specify shipitfile?

### ISSUE THREAD

**Issue by fr-kshibata** [shipitjs/shipit#128]
we have multiple layers of deployment 

level1/{shipitfile.js,level2}/{shipitfile.js,level3}/shipitfile.js

is there a way to change the default shipitfile to another filename to avoid confusion?

**Comment by timkelty** [comment]
Currently no.

Can you expand on your situation a bit?
You can't use [environments](
https://github.com/shipitjs/shipit#customising-environments) for this?

**Comment by timkelty** [comment]
@fr-kshibata Closing for now.
