### ISSUE TITLE
Rename blTask to blockingTask

### ISSUE THREAD

**Issue by neoziro** [shipitjs/shipit#13]

**Comment by kamagatos** [comment]
I don't like the name blTask too. I'd rather name it taskSync instead. Following the node.js naming convention for synchronous operations.

**Comment by neoziro** [comment]
@kamagatos it's not the same meaning, "xxxSync" operations in node are truely "synchronous":

```js
console.log('hey');
xxxSync();
console.log('ho');
```
"ho" will be displayed after "xxxSync()" will be completely done. It's not the same for us. The "blockingTask" prevent others tasks to run at the same time, but it is not a synchronous task.

**Comment by kamagatos** [comment]
I see. so yea blockingTask makes more sense then. I'll submit a pull request with the refactor.

**Comment by neoziro** [comment]
@kamagatos OK but on branch v2.0.0 please.
