### ISSUE TITLE
Specify multiple commands in array

### ISSUE THREAD

**Issue by Rudloff** [shipitjs/shipit#130]
Hello,
It would be nice to be able to run multiple commands like this:

``` js
shipit.remote(['foo', 'bar']);
```

I know I can use `&&` but I think it would easier to read that way.

**Comment by timkelty** [comment]
Would you expect it to concat with `&&` as a result, or wait for a response and then execute the next command?

**Comment by Rudloff** [comment]
I think both make sense so I don't really know which one is best.

**Comment by timkelty** [comment]
I see what you're saying, but I kind of think we should just keep it simple.
Easy enough to just do`['foo', 'bar'].join(' && ')` if you want it in one command, or 

```
shipit.remote('foo')
.then(shipit.remote('bar'))
.then(shipit.remote('baz'));
```

if you want them separate.
