### ISSUE TITLE
Unexpected behavior when more servers defined in default than in a specific environment

### ISSUE THREAD

**Issue by sangaline** [shipitjs/shipit#137]
Imagine a situation where you have a set of servers that you want to be common between multiple environments but then want to override the servers in other environments. Here is one possible example:

``` javascript
const config = {
  default: {
    servers: [ 'server01', 'server02'],
  }, development: {
    servers: ['devserver'],
  },
  ...
}
```

In this situation, I would expect the `development` configuration to include only `devserver` (or possibly `server01`, `server02`, and `devserver`). What actually happens is that it includes `devserver` and `server02` but not `server01`. It's a bit subjective, but this behavior seems unintuitive to me and might just be an unintended consequence of using `lodash.merge`.

What do you think of making any environment-specific `servers` definitions completely override the default one?

**Comment by timkelty** [comment]
@sangaline I agree! PR looks good, I'll merge it in.

**Comment by timkelty** [comment]
Ya know, looking at it now, it seems like maybe making an exception for `servers` isn't the way to go...it seems like maybe we should be using `_.assign` instead, always overwriting anything you have in your environment.

Do you agree?

**Comment by timkelty** [comment]
I merged in the `_.assign` solution and used your test.
Thanks!
