### ISSUE TITLE
`nvm use X` before all commands?

### ISSUE THREAD

**Issue by getvega** [shipitjs/shipit#139]
I tried in `shipit-nvm` repository (https://github.com/callerc1/shipit-nvm/issues/5) but I might get more answers here.

Is it possible to prefix a command to all `shipit.remote` commands?
That might be a bad practice as it would prefix commands that do not need this `nvm use XXX` prefix (e.g. shipit shared folders).

**Comment by timkelty** [comment]
@getvega Hmmm no nothing like that is currently available.
However, I don't see why you couldn't something like this:

```
shipit.remote('nvm use XXX')
.then('someOtherCommand')
.then('nvm use default')
```
