### ISSUE TITLE
[Task] shipit-s3 to sync some assets with Amazon S3 bucket

### ISSUE THREAD

**Issue by welcoMattic** [shipitjs/shipit#14]
I just init a new repo to write this task for S3 bucket (idea come from [gulp-s3 module](https://www.npmjs.com/package/gulp-s3)):

https://github.com/welcomattic/shipit-s3

Feel free to fork if and submit PR ;)

**Comment by neoziro** [comment]
@welcoMattic nice, I think we will proceed like grunt, just create tasks you need. If it grows we can put back the task in the organization.

**Comment by neoziro** [comment]
@welcoMattic I will develop only tasks I need, for now, only the "shipit-deploy" but if I need one, I will develop it.

**Comment by neoziro** [comment]
@welcoMattic ping me by email when your plugin will be stable, I will add it in the readme of Shipit.

**Comment by welcoMattic** [comment]
@neoziro Ok, I'm hard working on it. I code a shipit-aws module, to add any Amazon service in the future.
