### ISSUE TITLE
Run command on specific server

### ISSUE THREAD

**Issue by DuanPengfei** [shipitjs/shipit#143]
```
// my config
shipit.initConfig({
    production: {
        servers: [{
            "host": "192.168.33.101",
            "user": "vagrant"
        }, {
            "host": "192.168.33.102",
            "user": "vagrant"
        }]
    }
});
```

Is there any way to run command on one server `192.168.33.101`，but not run this command on the other server `192.168.33.102`

**Comment by timkelty** [comment]
Not directly, no. `shipit.remote` is intended to run on all servers.

It can be done though, [see example](https://github.com/timkelty/shipit-ssh/blob/master/tasks/ssh/index.js).

Will add this as a feature request.

**Comment by DuanPengfei** [comment]
👌

**Comment by timkelty** [comment]
After thinking this over, I think the best way to handle this is actually to just assume `shipit.remote` commands always go to all servers, and instead use environments to target.

Example:
```
// my config
let web01 = {
    "host": "192.168.33.101",
    "user": "vagrant"
};
let web02 = {
    "host": "192.168.33.102",
    "user": "vagrant"
};

shipit.initConfig({
    production: {
      servers: [web01, web02],
    },
    web01: {
      servers: [web01],
    },
    web02: {
      servers: [web02],
    },
});
```

**Comment by DuanPengfei** [comment]
这是一个好的解决办法，有时候真的是只需要稍微转变一下思路就好了 😊

**Comment by DuanPengfei** [comment]
This is a good solution, and sometimes it is really just a little change in thinking about it. 😊

**Comment by timkelty** [comment]
@DuanPengfei glad you think so!
