### ISSUE TITLE
This delete all my project

### ISSUE THREAD

**Issue by Masterchoc** [shipitjs/shipit#145]
I just ran the following example and filling with the default example settings, and replacing with mine, et this removes my entire project.

Glad i had a backup...

wtf ?

**Comment by timkelty** [comment]
What example?

I'm assuming this is a misunderstanding of the `workspace` option. https://github.com/shipitjs/shipit-deploy#workspace

Please read the description. This is NOT your project path.

**Comment by timkelty** [comment]
FWIW, you're not the only person this has happened to. Next major release may rename this to something more self-explanatory than `workspace`

**Comment by Masterchoc** [comment]
Thanks,

I clearly misunderstood the means of the workspace options, if i got it it's just for a temporary syncing directory ?

At first I thought this represented the location of my local project, but clearly not lol.

+1 For the renaming of the options, because it's very confusing, especially if you dont read the all docs before.

That's why i gave up for now, i dont want to make more mistakes on the project i working on now, i will come back later with some test to assert that i'm not doing something wrong.

For now, i just use basically git, with a simple post-receive hook, and a Makefile for deploying my NodeJs project and it works fine, but i really like the simple way shipit purpose
