### ISSUE TITLE
Clarify "workspace" option.

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#148]
Frequently misunderstood.
People think this is the path to their project, not a tmp location.

**Comment by ChennyBaBy** [comment]
👍 I got confused at this.

**Comment by fgallardograzio** [comment]
I'd consider renaming "workspace" to something else, but mainly I'd strongly suggest to have shipitjs automatically use a temp folder as a convention, and clean it afterwards. For this you may use nodejs's [os.tmpdir()](https://nodejs.org/api/os.html#os_os_tmpdir) or something similar.

Users who are sure they know what they're doing and for whatever reason don't want this default behaviour can of course specify a different path in their `shipitfile.js`.

A task that permanently deletes files from disk without the user explicitly confirming "yes, I'm sure I want those files gone forever" is very risky. Even more so when the main purpose of the task is to deploy your app, which could be thought of as exactly the opposite of deleting your app.

**Comment by neoziro** [comment]
Workspace is changed in v4. It has now two different behaviours, in shallowClone and in no-shallowClone:

- `shallowClone: true`: a new temporary workspace is generated each time you deploy.
- `shallowClone: false` (default): same behaviour as before except that we will never run `rm -rf` in the workspace (before it was in `shallowClone: true`). I also added a warning if the workspace is set in the current directory.

https://github.com/shipitjs/shipit/pull/157/commits/25050848e3d5c250d1489402ebf5648af5321539
