### ISSUE TITLE
Shipit object only exposes config for current environment 

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#15]
Normally you're only concerned with your current environment, but some tasks may want to interact with other environment configs.

For example, a [database syncing task](https://github.com/timkelty/shipit-db). Suppose you wanted to be able to sync a database between 2 remotes with something like:
```
shipit production db:push:development
```

**Comment by neoziro** [comment]
You must find a way to do it in your task, because it will not be built-in in Shipit, it can be very dangerous to mix environment.

**Comment by timkelty** [comment]
Sounds good, thanks.
