### ISSUE TITLE
Serial remote command

### ISSUE THREAD

**Issue by miccrun** [shipitjs/shipit#151]
Is it possible to run a remote command on multiple servers in serial? At a time only one server is running the command, not in parallel.

**Comment by timkelty** [comment]
@miccrun Sorry can you clarify: are you looking to run commands run _in parallel_ or _serially_ (these are opposite).

**Comment by miccrun** [comment]
I'm looking to run commands serially, one by one.

**Comment by timkelty** [comment]
Then you want to use blTask: https://github.com/shipitjs/shipit#shipitbltaskname-deps-fn
