### ISSUE TITLE
How can I stop local env var expansion when using shipit.remote

### ISSUE THREAD

**Issue by vjpr** [shipitjs/shipit#152]
When I do the following:

```
await shipit.remote(`echo $PATH`)
```

it replaces `$PATH` with my local machine's $PATH.

Looked here but can't seem to fix it: http://stackoverflow.com/questions/13826149/how-have-both-local-and-remote-variable-inside-an-ssh-command

**Comment by vjpr** [comment]
Workaround:

```
await shipit.remote('printenv PATH')
```

**Comment by neoziro** [comment]
@vjpr you should escape your `$`, try `echo \$PATH`
