### ISSUE TITLE
Deleted all local file while deploying

### ISSUE THREAD

**Issue by samundrak** [shipitjs/shipit#159]
I was trying shipit for first time,
after some configuration when i hit deploy it deleted all my local project 
and i lost all my recent works.
![image](https://user-images.githubusercontent.com/3079452/29984143-bc2367f4-8f78-11e7-9529-8ba26f9b5ac4.png)

**Comment by samundrak** [comment]
path of mine local and server are same..
so is there conflict with this?
like in local /home/samundrak/app also in server /home/samundrak/app

**Comment by timkelty** [comment]
Please post your shipit config.

I suspect you incorrectly set the `workspace` option to your project directory - Read the description: https://github.com/shipitjs/shipit-deploy#workspace

**Comment by neoziro** [comment]
@timkelty workspace is terrible, we need to tackle it

**Comment by samundrak** [comment]
Sorry my ship config also got deleted with my project.

**Comment by neoziro** [comment]
Closed, #148 is very important.
