### ISSUE TITLE
shipit.localCopy command?

### ISSUE THREAD

**Issue by dcsan** [shipitjs/shipit#163]
I see the remoteCopy command 
https://github.com/shipitjs/shipit#shipitremotecopysrc-dest-options-callback
https://github.com/shipitjs/shipit/blob/master/lib/shipit.js#L247

is there a way to copy FROM a remote to a local dir with that command?

**Comment by neoziro** [comment]
@dcsan yes using direction parameter, but it is not really documented, you can take a look to [ssh-pool](https://github.com/shipitjs/ssh-pool).
