### ISSUE TITLE
default command / menu option?

### ISSUE THREAD

**Issue by dcsan** [shipitjs/shipit#165]
is there a way to run a command without an env?

I want to make a simple menu of the commands available in a script.
but it will require running `shipit ENV menu`

I was looking for just a default command, ie if you just run `shipit` with no arguments

anyone else have a good approach for this? a bit like a `usage: xxx` statement.

**Comment by neoziro** [comment]
@dcsan no there is no way to do it for now.

You can try to make an alias: `alias ship="shipit production"`
