### ISSUE TITLE
SSH proxy and dynamic AWS EC2 target instance selection

### ISSUE THREAD

**Issue by makered** [shipitjs/shipit#17]
Probably too early at this stage, but just wanted to mention a couple of features that would be great to have for anyone deploying to Amazon Web Services / VPC environment. 

1. SSH proxy support - useful when deploying to hosts in a VPC behind a NAT form an external CI server/service. Allows the NAT instance to be used as an SSH proxy so we can reach our hosts that are not exposing SSH to the world (just a sample use case).

2. Choose target EC2 hosts dynamically based on tags - great for an environment where number of hosts and their identifiers (IPs/hostnames) change often (e.g. autoscaling). AWS is queried at build time and a list of target EC2 instances is compiled based on how instances are tagged (e.g. project/roles/stage tags).

We come from Capistrano and it gives us SSH proxy ability directly and EC2 tag parsing through a third-party add-on (https://github.com/forward3d/cap-ec2). Would love to see similar features in Shipit in the future.

Thanks

**Comment by jakiestfu** [comment]
:+1:  this feature

**Comment by neoziro** [comment]
I don't plan to do it at all, you can create a Shipit plugin to do that if you want. SSH Proxy is part of https://github.com/neoziro/ssh-pool, please add an issue or propose a pull-request for that if you need it.
