### ISSUE TITLE
call one shipit task from another?

### ISSUE THREAD

**Issue by dcsan** [shipitjs/shipit#170]
How can I call one task from another?

I know i can use dependencies  `shipit.blTask('transferDb', ['mongodump'].. `

but I want to be able to call a task with parameters...:

```
  shipit.blTask('mongodump', async function (opts) {
    let dbName = opts ? opts.dbName : shipit.config.dbName
```

how can I call that? I tried:

```js
    shipit.start('mongodump', {
      dbName: shipit.config.target_db
    })
```

also will `shipit.start` 'wait' for that task to run? or it just starts it off?

**Comment by dcsan** [comment]
I guess I can just use a normal function call, and putting it inside the 

```
module.exports = function (shipit) {

```

gives access to the shipit object too.

**Comment by neoziro** [comment]
@dcsan use events for that
