### ISSUE TITLE
Deploy to Windows

### ISSUE THREAD

**Issue by sceee** [shipitjs/shipit#171]
Hi,

what is necessary to deploy to Windows, does shipit / shipit-deploy support Windows?

In https://github.com/shipitjs/shipit-deploy/issues/72 I saw that there was a discussion about Windows support but it was 2 years ago and I am unsure if shipit / shipit-deploy supports Windows (as target) nowadays.

**Comment by neoziro** [comment]
@sceee I am not using Windows so Windows support is brought by community, I can't assert that Shipit supports Windows.

**Comment by sceee** [comment]
@neoziro thanks for the fast answer.
Do you know if it was used on Windows-to-Windows before? I'm already stuck at calling shipit locally since it tries to execute `rm -rf /tmp/deployment-preparation` which is not possible under Windows.
I also saw this documentation https://github.com/shipitjs/shipit/wiki/Deploying-from-Windows but it seems it involves changing the system configuration to have a Linux like bash which is not what I want.

**Comment by pbarbiero** [comment]
sceee, I have had some success (and submitted a few pulls for v4 to improve things) but you definitely should run this under a bash environment in windows. Better yet, if you install git-for-windows and open its bash terminal (or use cmder with git-for-windows integrated) you will have much better success.

**Comment by neoziro** [comment]
I close it, feel free to reopen this issue after v4.
