### ISSUE TITLE
How to obtain the environment currently deploying

### ISSUE THREAD

**Issue by brecke** [shipitjs/shipit#174]
Hi guys,

I'm trying out shipit on a large project and I'm loving the work you guys did so far, many thanks!

One issue I'm facing has to do with the fact that after deploy I reload the servers in a different way, depending on which environment I'm using. So, for instance, let's say that for `production` I run `reloadX` but for `staging` I need to run `reloadY`.

My immediate quest was looking for the environment variable I've invoked through `shipit <environment> deploy` but couldn't find it. Is there a way I can get it somewhere?

Other ways of achieving this would be to create another key in the production / staging objects, but this would be redundant if there the above were true. Other than this, does anyone have any more ideas? I feel I'm missing something here.

**Comment by neoziro** [comment]
The best way to achieve it actually is to create another entry in the configuration. Rely directly on environment is not a good thing IMO.

**Comment by brecke** [comment]
I think I found it in the meantime: `shipit.environment` does the trick. Closing.
