### ISSUE TITLE
yarn tasks don't block

### ISSUE THREAD

**Issue by dcsan** [shipitjs/shipit#176]
I'm using yarn for deployments (like most people now I guess) and find that shipit tasks don't finish in order. The `yarn install` will immediately come back as complete, but then the deploy will fail immediately.

I'm guessing this is something to do with yarn itself doing tasks in parallel... but would seem to be a huge problem for shipit unless i'm using it wrong...

doing something like this:

```
  shipit.blTask('yarn-server', async function () {
    let cmd1 = `cd ${deployDir}/server && yarn install --frozen-lockfile`
    shipit.remote(cmd1)
    return shipit.log('yarn done')
  })
```

----

In general - for any tasks - even ones that behave I noticed the blocking behavior doesn't seem to work unless I `return ...` something from the task also. eg:

```
  shipit.blTask('yarn-server', async function () {
    let cmd1 = `cd ${deployDir}/server && yarn install --frozen-lockfile`
    shipit.remote(cmd1)   // not returning anything, this won't block
  })
```
but not quite sure. Something unexpected is happening so that 'synchronous tasks' are really hard to predict the behavior of. Maybe you have some guidance or docs to point to here...

**Comment by neoziro** [comment]
`shipit.remote()` is returning a promise, you have to return it, else Shipit will not wait.

**Comment by dcsan** [comment]
since the function itself is `async` perhaps that is returning a promise anyway? but unclear to me when it would be resolved.

```
  shipit.blTask('yarn-server', async function () {
```

**Comment by neoziro** [comment]
You missed `await` in front of `shipit.remote(...)`.
