### ISSUE TITLE
How do I get the result of a command?

### ISSUE THREAD

**Issue by thelinuxlich** [shipitjs/shipit#18]
shipit.local("pwd", function(result) { console.log(JSON.stringify(result)) }) returns a huge object

**Comment by neoziro** [comment]
```js
shipit.loca('pwd').then(function (res) {
  console.log(res.stdout);
});
```

**Comment by thelinuxlich** [comment]
Doesn't work, res.stdout returns undefined

**Comment by thelinuxlich** [comment]
Actually shipit.local returns the correct result, shipit.remote returns undefined

**Comment by neoziro** [comment]
@thelinuxlich maybe you don't have any stdout?

**Comment by thelinuxlich** [comment]
so how shipit.remote without callback returns the result?

**Comment by thelinuxlich** [comment]
result[0].stdout did the trick on .remote()

**Comment by neoziro** [comment]
I don't understand, you can use callback or promises. Normally, you can do exactly like with local:

```js
shipit.remote('pwd').then(function (res) {
  console.log(res.stdout);
});
```

**Comment by neoziro** [comment]
@thelinuxlich ah yes, sorry.. this is because it's possible to specify multiple servers. Is there any mistakes in the readme?

**Comment by thelinuxlich** [comment]
I think you should extend the "ls -lah" command examples to show how to get the result both local and remote, this could be confusing

**Comment by neoziro** [comment]
Done #19

**Comment by thelinuxlich** [comment]
nice!
