### ISSUE TITLE
how do I run a task against multiple environments?

### ISSUE THREAD

**Issue by dcsan** [shipitjs/shipit#183]
If I'm correct one of the benefits of shipit is parallel deploys to multiple servers?

eg If I want to update my code for multiple app instances, with a config something like:

```js
  multi: {
    servers: [
      {
        login: 'deployer@bot-wiz.com',
        deployDir: '/mnt/ext1/app1'
      },
      {
        login: 'deployer@bot-wiz.com',
        deployDir: '/mnt/ext1/app2'
      }
    ],
  },
```

Does shipit provide some sugar to enable this or do I have to loop through `servers` myself?

Or, is there a way to call shipit with multiple environments, so I could "compose" the list of envs?

`shipit app1 app2 deploy` 

---

PS I'm working on a FAQ.md file with some of the questions from the issues here. Hopefully this will help others without cluttering up the issues too much.

**Comment by dcsan** [comment]
related question in FAQ (will send a PR after I fill it out a bit)
https://github.com/dcsan/shipit/blob/master/ressources/faq.md#how-to-run-a-task-against-multiple-environments

**Comment by neoziro** [comment]
This is not possible, it is by design. Environments are similar to environment variables.

You can't do `NODE_ENV=development NODE_ENV=production npm start`, it is the same for Shipit.

I suggest you to create an environment with all servers from env1 and from env2.
