### ISSUE TITLE
Error: spawn /bin/sh ENOENT

### ISSUE THREAD

**Issue by nanom1t** [shipitjs/shipit#185]
Hi, 

I'm using shipit in my projects and it worked well. However, I've faced with strange issue and I don't know how to fix it. I'm trying to deploy project from git repository:
```
$ shipit dev deploy
Running 'deploy:init' task...
Finished 'deploy:init' after 1.33 ms
Running 'deploy:fetch' task...
Create workspace...
Workspace created: "/tmp/app"
Initialize local repository in "/tmp/app"
Running "git init" on local.
'deploy:fetch' errored after 14 ms
Error: spawn /bin/sh ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
``` 
Here is my config:
```
var path = require('path');

module.exports = function (shipit) {
    require('shipit-deploy')(shipit);
    require('shipit-shared')(shipit);

    shipit.initConfig({
        default: {
            workspace: '/tmp/app',
            dirToCopy: '/tmp/app/www',
            deployTo: '/var/www/public_html/app.net/www',
            repositoryUrl: 'https://user@bitbucket.org/user/app.git',
            branch: 'master',
            ignores: ['.git', 'node_modules'],
            rsync: ['--del'],
            keepReleases: 3,
            deleteOnRollback: false,
            key: '~/.ssh/id_rsa',
            shallowClone: false,
            shared: {
                overwrite: true,
                dirs: [
                    { path: 'public/photos', overwrite: true, chmod: '-R 755' }
                ]
            }
        },
        dev: {
            servers: 'user@192.168.1.5:22',
            branch: 'develop'
        },
        production: {
            servers: 'user@app.net:22',
            branch: 'master'
        }
    });

    shipit.on('deployed', function () {
        shipit.start(['run']);
    });

    shipit.blTask('run', function () {
        shipit.start('pm2:start');
    });

    shipit.blTask('pm2:start', function () {
        return shipit.remote('source ~/.nvm/nvm.sh && pm2 start ' + shipit.currentPath + '/process.json');
    });
};
```
Previously everything worked good. 

```
$ shipit --version
4.0.2
```
Please help me to fix this issue.

**Comment by neoziro** [comment]
When does it happen? After v4+ update or it previously worked with v4+?

**Comment by nanom1t** [comment]
@neoziro Thank you for the response. This happens also before update. I used v3 and after getting this error, I decided to update it, but it does not help.

**Comment by neoziro** [comment]
I think this is related to your environment, I found [another issue](https://github.com/nodejs/node/issues/9644) and it is a Node related issue. I am sorry I can't help and it is probably not relative to Shipit.

**Comment by nanom1t** [comment]
I'm using Node.js v8.11.1 LTS, Ubuntu 16.04 LTS and deploying from MacOS High Sierra 10.13.3. 

Is there a way to see verbose information about this error?

**Comment by neoziro** [comment]
I don't know, you should try to look for on Google if it could be solved "Error: spawn /bin/sh ENOENT".

**Comment by nanom1t** [comment]
@neoziro I've tried different versions of Node.js (6.11.1, 6.14.1, 8.11.1, 9.10.1), but it does not help.

I think you should improve compatibility of Shipit with different environments. Especially creating new processes with child_process. Here is the way how PM2 fixed this issue - https://github.com/Unitech/pm2/commit/1df38b6117a47bdb50d795c71d947288703844f2

**Comment by nanom1t** [comment]
I've spent a lot of time and found that the problem is located in shipit-deploy package. The 2.5.1 version of this package works great in my environment and it worked good previously in my other projects before. However the v4 of this package generates Error: spawn /bin/sh ENOENT. `npm install shipit-deploy@2.5.1` helped me to fix this error.

**Comment by neoziro** [comment]
Thanks for investigated it, so it is a bug in v4. Will try to find it.

**Comment by neoziro** [comment]
Hmm OK, probably a missing `mkdirp` somewhere.

**Comment by RichAyotte** [comment]
I'm not sure what previous versions did, but I can confirm that it's a missing directory issue.

Something like the following used to work even when `frontendPath` was missing.
```js
await shipit.local(
  `yarn`
  , {
    cwd: frontendPath
  }
)
```

Simple fix.
```js
const fs = require('fs-extra')
await fs.ensureDir(frontendPath)
```

**Comment by RichAyotte** [comment]
Here's the problem. The `config.workspace` is ignored when shallowClone is true and some scripts depend on that path. 

https://github.com/shipitjs/shipit/blob/343fa7dfb41f507492eca315ceda52eaa1e6d703/packages/shipit-deploy/src/tasks/deploy/fetch.js#L24

```js
if (shipit.config.shallowClone) {
  const tmpDir = await tmp.dir()
  shipit.workspace = tmpDir.path
} else {
  shipit.workspace = shipit.config.workspace
  if (path.resolve(shipit.workspace) === process.cwd()) {
    throw new Error('Workspace should be a temporary directory')
  }
}
```

**Comment by minhchu** [comment]
@neoziro i suppose it should have a `mkdir` here
https://github.com/shipitjs/shipit/blob/343fa7dfb41f507492eca315ceda52eaa1e6d703/packages/shipit-deploy/src/tasks/deploy/fetch.js#L27-L32
while waiting for a patch, this is a work-around:
```
shipit.on("init", () => {
    return shipit.local(`mkdir -p ${shipit.config.workspace}`);
})
```

**Comment by wubzz** [comment]
Can confirm similar issue for us few Windows users. Getting `ENOENT` on `C:\Windows\system32\cmd.exe`. 

After applying the fix above this error goes away, but there seems to be several more issues least of which is local commands being run in the wrong directory despite setting `cwd` = `shipit.config.workspace`. It ends up trying to save a `package.json`  to `C:/Users/x/package.json` when install path is somewhere in windows tmp dir.

The issue with [invalid paths](https://github.com/shipitjs/shipit-deploy/issues/146) on windows seems to have escalated as well, as it now also applies to the `deploy:update` when trying to pack and deploy.
`Error: Command failed: cd /C:\Users\x\AppData\Local\Temp && tar --exclude "src" ...`

Will report back once I find a complete workaround for Windows users.

**Comment by vpratfr** [comment]
Got the same error on my side.

Applied the init hook without success.

Changed the workspace from `~/deploy` to `/home/vagrant/deploy` and it worked.

I guess the init hook is still needed but I think that is not the only issue.

**Comment by nanom1t** [comment]
is there any fixes for this issue?

**Comment by ozee31** [comment]
I have the same problem with shipit-cli 4.2 and shipit-deploy 4.1.4

```
Initialize local repository in "/tmp/itmv2-pp"
Running "git init" on local.
'deploy:fetch' errored after 11 ms
Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
