### ISSUE TITLE
Directory permissions for releases post 4.0 release

### ISSUE THREAD

**Issue by tim-field** [shipitjs/shipit#189]
Using version ^4 my release directory looks like this
`drwx------ 8 deploy deploy 4096 Apr 15 17:39 20180415052742/`

Using version ^1 my release directory looks like this.
`drwxrwxr-x 8 deploy deploy 4096 Apr 15 17:57 20180415054603/`

This breaks things for me where I have a `www-data` user reading from releases, post version 4 it can't get to my release directories at all.  Is there a workaround for this ?

**Comment by neoziro** [comment]
It's weird, I didn't change any code around permissions. I think you should change the `umask` (https://www.thegeekstuff.com/2010/04/unix-file-and-directory-permissions/), it is nothing relative to Shipit.

**Comment by tim-field** [comment]
:thinking: well reverting back to shipit v1 fixes the issue, so I think it must be related to shipit v4

**Comment by neoziro** [comment]
OK, I don't know what could be the problem, could you try to investigate?

**Comment by standingdreams** [comment]
I am having the same issue. The release directory is creating directories with `700` permissions (basically `rwx------`). I'm using the latest version of Shipit.

**Comment by neoziro** [comment]
I don't know why the behaviour has changed. The SSH command is the same as before, it is very weird.

**Comment by roxcity** [comment]
I am also facing the same issue. However, I am making it work by added chmod -R 755 . on release path for now.

**Comment by silentworks** [comment]
Yeah I am experiencing this same issue, I just create an extra task to change the permission based on the `published` event being fired.

```javascript
shipit.on('published', async () => {
  shipit.log(chalk.green('Changing directory permissions.'))
  await shipit.remote(`chmod +x ${shipit.releasePath};`);
  shipit.log(chalk.green('Permissions changed'))
})
```

**Comment by neoziro** [comment]
Anyone could try to fix it in Shipit?

**Comment by neoziro** [comment]
@silentworks same for me, but we need to fix it even it is a phantom bug 😅
