### ISSUE TITLE
[Improvement] Don't ask for ssh password on every action

### ISSUE THREAD

**Issue by kingio** [shipitjs/shipit#196]
When doing `shipit production deploy`, shipit will ask for ssh password on every action so you end up entering it over 10 times for a simple deploy.
Deployer asks once during the deploy and automatically reuses it when required.

**Comment by neoziro** [comment]
You should use a key and not a password.

**Comment by kingio** [comment]
Or switch back and keep using deployer which looks a better idea.

**Comment by yoonwaiyan** [comment]
While I understand that using a key is strongly recommended but I don't see a point of ShipIt not to support password authentication for ssh (unless unix has totally banned password-based authentication). I have this very same problem here, but I'm not in the decision of setting up to authenticate by key, and I was hopeful that this script is as flexible as Capistrano. I'm trying out ShipIt as the deployment tool for my NodeJS environment but it seems to have much more frictions than Capistrano if password is required for every remote call.

**Comment by neoziro** [comment]
I am open to password authentication, feel free to submit a PR to make it possible!

**Comment by ohmybrew** [comment]
The issue I'm having is my key is password protected, so every action it asks for the key. Other deployment solutions I've used leave the SSH connection open. Shipit seems to open and close it every action. Any tips?

**Comment by neoziro** [comment]
Shipit relies on `ssh` binary, that's why I think it will open a new ssh session each time. Right now it is the way it works. A better implementation would be to use a SSH library instead but it would be a full rewrite of Shipit. I will not do it, if someone want to be involved in the project and become maintainer he is welcome.

**Comment by ferleal** [comment]
One option is to configure your local ~/ssh/config with the option AddKeysToAgent yes
example
> ~/ssh/config 
```shell
Host web
        HostName server_ip
        User user_name
        Port port_num
        IdentityFile key_location
        AddKeysToAgent yes
```
Connect one time and it will save the key passphrase

It worked form me on OSX but it should work on Linux too.
