### ISSUE TITLE
'rsync' error when running command on windows

### ISSUE THREAD

**Issue by boedlen** [shipitjs/shipit#20]
I'm trying to deploy a small nodejs site to a an Ubuntu server that's on my local network.

So far i've made a simple test that's suppose to deploy a website to my server but i get this error:

    Branch merged.
    Finished 'deploy:fetch' after 3.52 s
    
    Running 'deploy:update' task...
    Create release path "/var/www/shipit-test/releases/20150203204754"
    Running "mkdir -p /var/www/shipit-test/releases/20150203204754" on host "192.168.1.200".
    administrator@192.168.1.200's password:
    Release path created.
    Copy project to remote servers.
    Remote copy "C:/Developer/shipit-test/deploy/" to "administrator@192.168.1.200:/var/www/shipit-test/releases/20150203204754"
    @192.168.1.200-err 'rsync' is not recognized as an internal or external command,

    @192.168.1.200-err operable program or batch file.
    'deploy:update' errored after 11 s
    Error: Command failed: 'rsync' is not recognized as an internal or external command, operable program or batch file.
    
    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)

My `shipitfile.js` looks like this:

    module.exports = function (shipit) {
      require('shipit-deploy')(shipit);

      shipit.initConfig({
        default: {
          workspace: 'C:/Developer/shipit-test/deploy',
          deployTo: '/var/www/shipit-test',
          repositoryUrl: 'https://github.com/boedlen/privat-repo.git',
          ignores: ['.git', 'node_modules'],
          keepReleases: 2,
          shallowClone: true
        },
        staging: {
          servers: 'deploy@192.168.1.200'
        }
      });
    };

My server is an Ubuntu Server, and my computer is a Windows 8 - 64bit, is this a windows related issue?

**Comment by neoziro** [comment]
Rsync is required to run Shipit, I don't know if it exists on Windows.

**Comment by jakiestfu** [comment]
@neoziro you won't explore a solution to this?

**Comment by neoziro** [comment]
@jakiestfu no I don't plan to support Windows.

**Comment by tamlyn** [comment]
Please consider making this explicit in the readme. The usual assumption is that node programs run anywhere node does.

**Comment by hamzawaqas-10p** [comment]
@neoziro Agreed with @tamlyn  - You should figure out if `rsync` is on path, if not, if `scp` could do the job and even if not; acknowledge the user.
