### ISSUE TITLE
Server wise configurable deployTo parameter

### ISSUE THREAD

**Issue by utsavkesharwani** [shipitjs/shipit#203]
Hello,

Is there a possibility to configure [deployTo](https://github.com/shipitjs/shipit#deployto) parameter differently for different [servers](https://github.com/shipitjs/shipit#servers)?

Thanks!

**Comment by neoziro** [comment]
You have to create several environment, "prod-1", "prod-2", etc..

**Comment by utsavkesharwani** [comment]
Hi @neoziro,

We've done the same. However, the issue is, I've to trigger `shipit <environment> deploy` command multiple times for deployment on production environments.

Of course I can write a simple node/bash script to automate this. But just was wondering if there is a better way to achieve this via Shipit.
