### ISSUE TITLE
shipit.local("npm run build") hang forever

### ISSUE THREAD

**Issue by 1c7** [shipitjs/shipit#211]
### 1. Problem code
```javascript
module.exports = shipit => {
  //... ignore config (like shipit.initConfig({... etc)
  shipit.task('build', async () => {
    await shipit.local("npm run build");
  });
  // ... ignore other un-relate code
}
```

### Expect to happen: 
`shipit.local("npm run build");` should work like manually run `npm run build`   
it should look like this. (take about 5-10 second to complete)
![image](https://user-images.githubusercontent.com/1804755/44697247-742d7380-aaad-11e8-9031-bf427d7d618a.png)
![image](https://user-images.githubusercontent.com/1804755/44697249-7a235480-aaad-11e8-9100-e6ea3905df15.png)

### Actually happen:
run following command hang forever (I been waiting for over a minute)
```
npx shipit staging build
```
this task only have one line of code
```
shipit.local("npm run build");
```
![image](https://user-images.githubusercontent.com/1804755/44697287-ab038980-aaad-11e8-8681-a6fb87725cc0.png)

not sure why it hang

### package.json
```json
{
  "name": "Vue.js-SPA-App",
  "description": //omit,
  "version": //omit,
  "author": //omit,
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack-dev-server --mode development --open --hot --port 8081 --host 0.0.0.0",
    "build": "cross-env NODE_ENV=production webpack --mode production --progress --hide-modules",
  },
  "dependencies": {
    //omit
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "ie 6-8"
  ],
  "devDependencies": {
    //omit
  }
}
```

# Thanks for any help in advance!

**Comment by sinnwell** [comment]
Same here. Trying to build a React Boilderplate project.

**Comment by rafaelbdb** [comment]
Any progress with this? I have a similar problem, but with `npm run build` directly.

**Comment by JaroslavKrenar** [comment]
We had a same issue and found a workaround by changing webpack params to:

`webpack.js --no-progress --display-error-details --hide-modules`

Shipit is not able to process a webpack progress output for some reason.

**Comment by neoziro** [comment]
@rafaelbdb I don't see the relation between ";" and the bug.

**Comment by rafaelbdb** [comment]
@neoziro That's why took me 2 days to figure it out... Doesn't make any sense, but worked for me.

**Comment by 1c7** [comment]
since I am not using shipit often enough these day. I am gonna close this issue. free feel to keep discussion going.
