### ISSUE TITLE
[Question] Reboot remote server

### ISSUE THREAD

**Issue by btxtiger** [shipitjs/shipit#222]
Is it possible to wait for remote server to reboot?
I tried just using an async function, but this causes shipit to fail
```sh
@127.0.0.1-err Connection to 127.0.0.1 closed by remote host.
@127.0.0.1-err Connection to 127.0.0.1 closed.
'reboot' errored after 2.84 s
Error: Command failed: ssh -tt -p 3022 pi@127.0.0.1 "sudo reboot"
Connection to 127.0.0.1 closed by remote host.
Connection to 127.0.0.1 closed.

```

**Comment by neoziro** [comment]
I don't think it is possible since a reboot will close the connection to the server. Maybe someone has an idea!

**Comment by utkarsh-dixit** [comment]
@btxtiger  The only way I can think of is to create a new blocking task using shipit.blTask and then wait for the server gettting up after you have rebooted. Try pinging the server few times and when it's up return something and this wouldn't affect any new tasks... Just to be safe, also set a maximum wait time, (usually ~1min) and if the server isn't ready by then, it will mean something is wrong with the server.
