### ISSUE TITLE
How to run "npm run build" after "fetched" event and before "update"?

### ISSUE THREAD

**Issue by aureliusm** [shipitjs/shipit#231]
I think the title says it all. I can't find it in the documentation - how to hook into the deploy process and execute certain commands like "npm run build" or "npm run install" before updating the server with the new release?

Thanks!

**Comment by neoziro** [comment]
Hello @aureliusm, I think you can use events. There are described in the readme.

**Comment by SleepWalker** [comment]
something like this:

```js
shipit.on('fetched', () => {
  shipit.start('app:build');
});

shipit.blTask('app:build', async () => {
  await shipit.local('yarn build');
});
```

And here is doc links:

- https://github.com/shipitjs/shipit#use-events
- https://github.com/shipitjs/shipit/tree/master/packages/shipit-deploy#workflow-tasks
- https://github.com/robrich/orchestrator

**Comment by aureliusm** [comment]
@SleepWalker Thanks! Managed to get it working.
