### ISSUE TITLE
Error when set current revision

### ISSUE THREAD

**Issue by congpeijun** [shipitjs/shipit#244]
Setting current revision and creating revision file.
Running "git rev-parse master" on local.
@ master
@ fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
@ Use '--' to separate paths from revisions, like this:
@ 'git <command> [<revision>...] -- [<file>...]'
'deploy:update' errored after 3.61 s
Error: Command failed: git rev-parse master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:198:13)
    at Pipe._handle.close (net.js:606:12)

**Comment by congpeijun** [comment]
Find out the reason

**Comment by congpeijun** [comment]
When use this in gitlab-runner, the comman `git rev-parse ` does not work well.

**Comment by fliptheweb** [comment]
@congpeijun hi! But how did you solve that?
