### ISSUE TITLE
Deployment stuck at heavy custom task

### ISSUE THREAD

**Issue by yongkylie** [shipitjs/shipit#251]
Library version: shipit-cli: "^5.1.0"; shipit-deploy: "^5.1.0"
Local machine: macOS Mojave 10.14.6 (18G95)
Remote server: Ubuntu 16.04 LTS

Deployment just stuck after heavy task. If I exclude the heavy task deployment run successfully.

In my case, when `webpack` task is being run it just never completes or just stucked (as shown in script below). The process of that task is approximately 3-4 minutes. If I don't run that task (by disabling it after update emitted), the deployment just finished without problem.

Here's my `shipitfile.js` content:
```
  require('shipit-deploy')(shipit);
  const path = require('path');

  shipit.initConfig({
    default: {
      repositoryUrl: 'https://user@gitlab.com/repository.git',
      branch: 'master',
      ignores: ['.git', 'node_modules'],
      keepReleases: 5,
      deleteOnRollback: false,
      deploy: {
        remoteCopy: {
          copyAsDir: false, // Should we copy as the dir (true) or the content of the dir (false)
        },
      },
    },
    staging: {
      servers: 'user@host',
      workspace: '/path/to/local/tmp/',
      deployTo: '/path/to/release/dir/',
    },
    staging2: {
      servers: 'user@host',
      workspace: '/path/to/local/tmp/',
      deployTo: '/path/to/release/dir/',
    },
  });

  shipit.on('updated', async () => {
    await shipit.start('npm:install');
    await shipit.start('webpack');
  });

  shipit.blTask('npm:install', async () => {
    await shipit
      .remote(`cd ${path.join(shipit.releasesPath, shipit.releaseDirname)} && npm install`)
      .then(() => {
        shipit.log('npm:install finished (in promise)');
      })
      .catch((e) => {
        shipit.log(`Looks like an error occurred ${e}`);
      });
  });

  shipit.blTask('webpack', async () => {
    await shipit
      .remote(`cd ${path.join(shipit.releasesPath, shipit.releaseDirname)} && npm run production`)
      .then(() => {
        shipit.log('webpack finished!');
      })
      .catch((e) => {
        shipit.log(`Looks like an error occurred ${e}`);
      });
  });
```

Am I doing it wrong? Any help would be appreciated.

**Comment by neoziro** [comment]
Hello @yongkylie, probably a timeout on SSH? Shipit could wait forever so the problem is probably in the underlying system command.

**Comment by yongkylie** [comment]
Hi @neoziro, thank you for your reply. Just as I thought, maybe the problem is in the SSH timeout since my server is in Europe and I am deploying from Asia Pacific.

I think there's no way to solve this except I have a strong and stable internet connection to do deployment. Do you have any thought or idea to get around this kind of issue? If so please tell me. I am closing this issue, but if anyone have any other solution, feel free to leave a comment.
