### ISSUE TITLE
Register a Shipit/Grunt task that is able to be called by shipit.start and Grunt

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#26]
Ran into this problem here:
https://github.com/timkelty/shipit-shared

Basically, I want to be able to:
* run `grunt shipit:development shared` manually, 
* Have it the `shared` automatically run on the `published` event (from shipit-deploy).

In this example, the task gets correctly called on `published`, but I'm unable to run it manually as `grunt shipit:development shared`:
```
module.exports = function (gruntOrShipit) {
  var shipit = getShipit(gruntOrShipit);
  require('./create-dirs')(gruntOrShipit);
  require('./link')(gruntOrShipit);

  registerTask(shipit, 'shared', [
    'shared:create-dirs',
    'shared:link',
  ]);

  shipit.on('published', function () {
    shipit.start('shared');
  });
};
```
If I pass `gruntOrShipit` to `registerTask` instead, I can run the grunt command manually, but the task is not run on `published` and I get the error: `Task 'shared' is not in your shipitfile`

Is there a good solution for this?

Might be more applicable in https://github.com/shipitjs/grunt-shipit, but I'm not sure.

**Comment by neoziro** [comment]
In you example, "publishd" is not correctly spelled.

I think that you can assume that gruntOrShipit is shipit, because you don't want to be compatible with the old grunt plugin. So you don't need getShipit, etc..

If you do that it should work:

```js
module.exports = function (shipit) {
  require('./create-dirs')(shipit);
  require('./link')(shipit);

  registerTask(shipit, 'shared', [
    'shared:create-dirs',
    'shared:link',
  ]);

  shipit.on('publshed', function () {
    shipit.start('shared');
  });
};
```

**Comment by neoziro** [comment]
If you want to be compatible with grunt, I think that you have to test if you are in grunt or in Shipit mode because it's not the same command to start tasks. `grunt.tasks.run(['shared'])` VS `shipit.start('shared')`

**Comment by neoziro** [comment]
You can also abstract the method to start the task, it's cleaner :).

**Comment by timkelty** [comment]
> I think that you can assume that gruntOrShipit is shipit, because you don't want to be compatible with the old grunt plugin. So you don't need getShipit, etc..

I'm not trying to be compatible with the old (pre-orchestator-based) grunt plugin, just https://github.com/shipitjs/grunt-shipit.

If I use your example from grunt (`grunt shipit:development deploy`), I get:
```
Loading "grunt-task.js" tasks...ERROR
>> TypeError: Object #<Object> has no method 'on'
```
Running from shipit works fine: (`shipit development deploy` or `shipit development shared`).

I was just following your lead from shipitjs/shipit-deploy with the `registerTask`/`gruntOrShipit` stuff.

**Comment by neoziro** [comment]
@timkelty yes I know, it's simple, when you have `gruntOrShipit` you need sometimes to test if it's grunt or Shipit to run the right command.

**Comment by timkelty** [comment]
Ok, sorry for the confusion :)

So it seems I just need to have a method to run/start from `gruntOrShipit`, as you suggested.

**Comment by neoziro** [comment]
Yes.
