### ISSUE TITLE
[question] shipit.releasePath is undefined

### ISSUE THREAD

**Issue by pioz** [shipitjs/shipit#264]
Hi, I'm trying to create a task to compile a binary. This is my shipitfile.js (shipit v5.1.0):
```js
// shipitfile.js
module.exports = shipit => {
  // Load shipit-deploy tasks
  require('shipit-deploy')(shipit)

  shipit.initConfig({
    production: {
      workspace: '/var/local/project_name',
      deployTo: '/var/local/project_name',
      repositoryUrl: 'git@github.com:pioz/project_name.git',
      servers: 'user@server.com'
    }
  })

  shipit.task('build', () => {
    const buildCmd = `cd ${shipit.releasePath} && go build *.go`
    shipit.remote(buildCmd)
  })
}
```
But `shipit.releasePath` is undefined. What is the correct way to get the release path?

**Comment by JaroslavKrenar** [comment]
`shipit.releasePath` is attached during **deploy:update** and **rollback:init** task: so maybe you are trying to call your task before these events.

Check [shipit-deploy](https://github.com/shipitjs/shipit/tree/master/packages/shipit-deploy) documentation for more information.

**Comment by pioz** [comment]
Oh, thanks. I had not seen the doc of shipit-deploy.
