### ISSUE TITLE
Status of repo

### ISSUE THREAD

**Issue by DanielTamkin** [shipitjs/shipit#281]
Hey all!

Was curious on the status of this toolkit. I'd love to utilize it for all my current and future CD tasks, however; a few deprecation warnings, and some gaps in the current documentation seem to indicate a sunset repo. @lukasoppermann has brought up some issues I've encountered myself, such as #227, #276, and #275. Regardless of the status, love the functionality & wide range of use-cases it supports! Hope to hear back 😀

**Comment by gregberge** [comment]
Hello @DanielTamkin, the project is stable but stale. I don't have time to work on it, there is no active maintainer. I think Shipit usage is very reduced as of today. Things have change a lot since I released it initially.
