### ISSUE TITLE
Rename blTask to blockingTask?

### ISSUE THREAD

**Issue by mikemaccana** [shipitjs/shipit#3]
Great tool! Currently using a custom built SSH deploy tool so looking forward to checking this out and contributing if need be. 

One small observation: `task`, `start`, `local`, `remote`, `remoteCopy` etc are all full word names matching both node and the DOM API. `blTask` though is contracted - renaming it to `blockingTask` would make things more consistent with both the rest of shipit and other JS apps.

**Comment by neoziro** [comment]
I am not very happy of this method, I hope that gulp 4 and Orchestrator will find a more elegant way to do that. Yes maybe I should rename it, I will wait because it's a breaking change and I don't want to create some alias.

**Comment by mikemaccana** [comment]
Understood and agreed, relying on gulp to take care of as many tasks as possible would be great. 👍

**Comment by neoziro** [comment]
I rely on orchestrator, the system used by gulp to manage tasks.
