### ISSUE TITLE
Could find 'npm', 'grunt', etc remotely

### ISSUE THREAD

**Issue by namiheike** [shipitjs/shipit#30]
I'm writing a task to remotely run `npm install` after deployed, but all I got is `bash: npm: command not found`

I've already set `nvm alias default` remotely.

I guess this issue is about environment path but I cannot figure out the exactly point.

Currently I'm using something like this
```
npm_path = '/home/deployer/.nvm/versions/io.js/v1.2.0/bin/npm'
shipit.remote(npm_path)
```

though I dont think it's the right thing to do.

**Comment by neoziro** [comment]
@namiheike with nvm it's always complicated because it's a bash script that is run and that put aliases in place. You just have to run `$NVM_DIR/nvm.sh` I guess.

**Comment by neoziro** [comment]
@namiheike is it fixed?

**Comment by phaibin** [comment]
I've also occurred this issue. And I've found the reason. There are some codes at the beginning of  .bashrc file:

```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```

But nvm shell line will be added at the end of this file. So ssh non-iterative command will not load nvm shell.

Just move nvm shell line above this line will solve this problem.
