### ISSUE TITLE
Consider adding methods for consistent CLI messaging/Inquirer-style prompts 

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#31]
Maybe this is not something you want included in Shipit directly, but I think it would be nice to expand on `shipit.log`, so that different Shipit tasks could have consistent CLI prompts and prevent authors from throwing around random `chalk` styles.
For example: `shipit.log.success`, `shipit.log.error`, `shipit.log.info`, `shipit.log.heading`

Along the same lines, I would like to see methods similar to Capistrano's `Capistrano::CLI.ui.ask` (probably using [Inquirer](https://github.com/SBoudrias/Inquirer.js)).

My first use case for both would be hooking into `shipit-deploy`'s `deploy` to display a summary of deploy information, with a Y/n prompt to continue with deploy.

Additionally, you could have a multiple choice selection for selecting your environment if you don't provide one in your `shipit...` command.

I'm happy to work on a PR for this stuff. Do you think you'd be willing to merge this kind of thing in?

**Comment by neoziro** [comment]
@timkelty hmm you know, I don't know if it's a good idea or not, I must think about it.

**Comment by neoziro** [comment]
I think it can be kind of cool to have a large choice of colors and tu be able to choose our module to make colors isn't? But for deploy plugin it can be great to have more information and an option to ask the branch.

**Comment by timkelty** [comment]
Yep, I'm mostly interested in the latter.

The way I'm thinking about it, you would still be able to do a `shipit.log` and use chalk to do whatever you want. The additional methods would just be for quick errors/successes to be styled consistently.

Additionally, at some point you may want to do something specific on a `shipit.log.error`, like flash a Growl/Notification Center message.

**Comment by neoziro** [comment]
@timkelty I think we should not complexify Shipit with that kind of stuff.

**Comment by timkelty** [comment]
Fair enough.

**Comment by timkelty** [comment]
I just added an example of this here: https://github.com/timkelty/shipit-ssh/blob/master/tasks/ssh/index.js#L15

Since the task really only applies for a single server, it prompts you to select a server if the `shipit.config.servers` is an array.

**Comment by neoziro** [comment]
@timkelty yes why not, we need to find a good API for the user to choose if he want to specify a branch hard-coded or if he prefers that we ask him.

**Comment by timkelty** [comment]
I assumed if you had the branch hard-coded, it would bypass the prompt.

However, maybe it is better to just set the default value of the prompt to the hard-coded value.
If users don't want the prompt if they already have it hard-coded, we could add an `alwaysAsk` `bool` config option or something.

**Comment by neoziro** [comment]
@timkelty I close it because the conversation about interactivity is relative to shipit-deploy project.

**Comment by timkelty** [comment]
For the Inquirer.js prompts for Shipit, see https://github.com/timkelty/shipit-captain
