### ISSUE TITLE
Provide method of comparing currently deployed revisions

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#34]
I was writing a notify task for Shipit and realized there was no way to get the SHA of deployed revisions.
In Capistrano, a `REVISION` file is created in the deploy path containing the SHA.

This allows us to set something like `shipit.currentRevision` / `shipit.previousRevision`, so, e.g. one could use them to compare with `git log` and print out a nice list of commits included in the current release.

It would also allow for methods like `pending` to show what hasn't been deployed yet.

I can work on PR for this, but let me know if this is something you'd merge in. Otherwise I'll just use `shipit-deploy`'s event hooks and do it [somewhere else](https://github.com/timkelty/shipit-utils)

**Comment by timkelty** [comment]
FYI - most of the methods necessary to do this already exist in the rollback task.

**Comment by neoziro** [comment]
@timkelty I think it's a good idea, OK for me, if it's a breaking change do it in v2, else you can do it in master.

**Comment by timkelty** [comment]
Sounds good.
