### ISSUE TITLE
Maybe there is a problem with rsync: --info=progress2 in Mac

### ISSUE THREAD

**Issue by carlosvillu** [shipitjs/shipit#35]
I´m working in Mac Yosemite with the las version 1.2.0

and I get this error:

```
Error: Command failed: /bin/sh -c rsync --exclude ".git" --exclude "node_modules" -az --info=progress2 -e "ssh " /tmp/force-front/ deployer@188.166.23.183:/var/www/force-front/releases/20150224162223
rsync: --info=progress2: unknown option
```

Seem like is a error from the --info param. Is working that for you in your Mac?!

Thx,

**Comment by vpratfr** [comment]
I also get this on Debian and Vagrant image from scotch.io

    Warning: Command failed: rsync: --info=progress2: unknown option
    rsync error: syntax or usage error (code 1) at main.c(1453) [client=3.0.9]

They both have rsync 3.0.9

**Comment by neoziro** [comment]
It's now reverted, nor more default progression, it's not compatible with all rsync version. You can update shipit to fix it.

**Comment by vpratfr** [comment]
Worked. Thanks.

**Comment by carlosvillu** [comment]
Thx!

**Comment by vjpr** [comment]
Would be cool to check for v3 and use it.

```
  async function isRsyncV3() {
    const rsyncVersion = await shipit.local(`rsync --version`)
    return rsyncVersion.stdout.match(/version (3\.\d\.\d)/)
  }
```
