### ISSUE TITLE
remoteCopy with Array

### ISSUE THREAD

**Issue by e-jigsaw** [shipitjs/shipit#36]
Hi,

I want to set Array in `remoteCopy` source. Example:

```coffee
shipit.remoteCopy ['hoge', 'fuga'], '/tmp/piyo'
```

Or do you have this other something good way?

Thanks

**Comment by neoziro** [comment]
I don't understand what do you want to do. Do you want to copy two files in a folder?

**Comment by neoziro** [comment]
`remoteCopy` uses rsync, so you can probably refer to rsync documentation to understand how it works.

**Comment by e-jigsaw** [comment]
Yes, I want to copy two files in a folder. I read rsync document and I tried `shipit.remoteCopy 'hoge fuga', '/tmp/piyo'`. It works. Thanks your support!
