### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by pdavid0** [shipitjs/shipit#37]
shipit js just deleted my entire workspace AND CRASHED LEAVING ME WITH NO WORKSPACE.

I lost 8h of work. What do I do now ?

**Comment by neoziro** [comment]
@pdavid0 you commit more often! I am sorry, it's weird... Did you understand what was the problem?

**Comment by pdavid0** [comment]
Yes , totally my fault ... :(     ( sorry for aggressive tone)

(I lost the crash logs)

Shipit seemed to have choked on removing node_modules : Permission denied.
Then common error message from child_process that died.

Then no more files, not even shipit.js

**Comment by neoziro** [comment]
Hmm OK, don't know what's going on sorry.

**Comment by skinofstars** [comment]
Old and closed issue, I know, but there is a chance that `workspace` was pointing to the project dir. The name kinda suggests it should be your project's workspace. 

I had `workspace` pointing to `.` and was happy to see `rm: cannot remove directory: ‘.’`.

Oddly, this was a perfectly valid option on the old grunt shipit.

**Comment by masterkorp** [comment]
@skinofstars This could be it, the ``workspace`` is a bit misleading.

**Comment by vjpr** [comment]
`workspace` is misleading. I nearly did the same before I read the docs. There should be a check at least for `/` and `process.cwd()`.
