### ISSUE TITLE
Is there a list of all know shipit tasks? (3rd party and official)

### ISSUE THREAD

**Issue by callerc1** [shipitjs/shipit#39]

**Comment by neoziro** [comment]
@callerc1 no, but I will try to do it in the readme.

**Comment by callerc1** [comment]
@neoziro awesome thats great. I was wandering if anyone has tackled a `"shipit-npm"` package that is based on the concept of https://github.com/capistrano/composer/

**Comment by neoziro** [comment]
@callerc1 I don't know, @timkelty has done a lot of plugins, but I don't know if there is one like that.

**Comment by timkelty** [comment]
@callerc1 Are you looking for a `composer` task? I actually have one I just need to publish. I'll do that this week.

**Comment by timkelty** [comment]
Or are you looking for something that runs an npm command before deploying?

**Comment by callerc1** [comment]
Looking to run npm commands as part of the deploy process. Eg on "updated" event npm install. 





Cheers

Chris

**Comment by timkelty** [comment]
@callerc1 Is there a reason you don't want to do that stuff locally in the shipit workspace? (on the `fetched` event?

**Comment by timkelty** [comment]
Kind of a toss up, but that way you don't have to worry about deps on your server, which is why I do it locally.

**Comment by callerc1** [comment]
Because I've noticed some issues with  some of my app dependencies and npm installing direct on the box seems to fix it. That's something I can double check tho. Event callback aside I think an shipit npm equivalent to the cap composer gem that mimics the task functionality would be really helpful. I'll probably make a start on something later this week.

**Comment by callerc1** [comment]
I think perhaps having the option to change the callback listener as an option could work, that way it covers both scenarios.

**Comment by timkelty** [comment]
Ok - I'll let you know if I push anything out.

**Comment by callerc1** [comment]
Awesome.

**Comment by timkelty** [comment]
@neoziro could be a good use for a Github wiki on this repo?

**Comment by neoziro** [comment]
@timkelty I think we can put all in the readme, the module is quite simple.

**Comment by outrunthewolf** [comment]
Yeah I would like to see a list of events. I'm trying to populate server addresses before I run any deployments, and I can't figure out which task to bind to.

**Comment by timkelty** [comment]
@outrunthewolf the events are all listed here: https://github.com/shipitjs/shipit-deploy#workflow-tasks

**Comment by outrunthewolf** [comment]
Awesome. Whats the syntax for using that:

    shipit.on('deploy:init', function() {
    });

Is that right?

**Comment by timkelty** [comment]
```
shipit.on('deploy', function() {
});
```
The name of the event is where it says
>  Emit event "deploy".

**Comment by callerc1** [comment]
@timkelty @neoziro i published this just now. would be great to have your thoughts:

https://www.npmjs.com/package/shipit-npm

Cheers

**Comment by timkelty** [comment]
Nice! I was considering just making a `shipit-package-managers` to do this, `composer`, `bower`, `bundler` etc.

**Comment by neoziro** [comment]
@callerc1 @timkelty thank you!

**Comment by neoziro** [comment]
Now in the readme, I close it.
