### ISSUE TITLE
How to get the result of a command run in the remote.

### ISSUE THREAD

**Issue by masterkorp** [shipitjs/shipit#41]
On a simple task, I want to check whether a run is run successfully, based on the exit code.

Example, I want to know a directory exists on the server:
```javascript
shipit.remote('test -d /my/path/on/all/the/servers/')
````

How do I analyze the result of this command ?

**Comment by neoziro** [comment]
@masterkorp 

> The callback gets the arguments (error, stdout, stderr). On success, error will be null. On error, error will be an instance of Error and error.code will be the exit code of the child process, and error.signal will be set to the signal that terminated the process.

So for you, if you enter in the "then", then you can assume a status code of 0.
If you enter in "catch", you can check the status code using `error.code`.

```js
shipit.remote('test -d /my/path/on/all/the/servers/')
.then(function () {
  console.log('It exists!');
)
.catch(function (error) {
  console.log('It doesn\'t exist!', error.code);
});
```

**Comment by masterkorp** [comment]
@neoziro Thank you!
