### ISSUE TITLE
How to orchestrate tasks

### ISSUE THREAD

**Issue by masterkorp** [shipitjs/shipit#42]
I want to perform some checks on all the servers where the code will be deployed. But I would like to run a certain task on all the servers, before moving to the deploy tasks.
I know this could be 2 separated shipit calls, but it would be great to make the a single call.

Is this what ``blTasks`` do ?

**Comment by neoziro** [comment]
@masterkorp I don't know what do you need, you can use deploy hooks to run tasks, or just the CLI using `shipit env task1 task2`. `blTask` create a task that will prevent other task to run in parallel (like Grunt).

**Comment by masterkorp** [comment]
How do I create a task that prevents it from running in parallel ?

**Comment by neoziro** [comment]
Using 'blTask".

**Comment by masterkorp** [comment]
I think ``blTask`` is not working or I am using it wrong.

Using [shipit-deploy](https://github.com/shipitjs/shipit-deploy)
```javascript
  shipit.on('updated', function () {
    shipit.start(['npm-install', 'build-assets'])
  });
```

**Comment by neoziro** [comment]
I think your "npm-install" task is not correctly defined, please copy it.

**Comment by masterkorp** [comment]
Here it goes:
``` javascript
  shipit.blTask('npm-install', function () {
    shipit.log(chalk.green('Installing dependencies on '+ shipit.releasePath));
    shipit.remote('cd ' + shipit.releasePath + ' && npm install')
    .then( function () {
      shipit.log(chalk.green('Successfully installed dependencies'));
    })
    .catch( function () {
      shipit.log(chalk.bgRed('Failed to install dependencies'));
    });
    shipit.emit('installed-packages')
  });
```

Also I failed to use the ``remote`` method like 
```javascript
 shipit.remote('npm install', {cwd: shipit.releasePath})
```

**Comment by neoziro** [comment]
@masterkorp if you don't return the promise it doesn't know when the task is finished! (cwd doesn't work on remote yet).

**Comment by masterkorp** [comment]
@neoziro I am new to Javascript and promises can you give me an example of what I am doing wrong ?

**Comment by neoziro** [comment]
```js
  shipit.blTask('npm-install', function () {
    shipit.log(chalk.green('Installing dependencies on '+ shipit.releasePath));
    return shipit.remote('cd ' + shipit.releasePath + ' && npm install')
    .then( function () {
      shipit.log(chalk.green('Successfully installed dependencies'));
      shipit.emit('installed-packages');
    })
    .catch( function () {
      shipit.log(chalk.bgRed('Failed to install dependencies'));
    });
  });
```

**Comment by neoziro** [comment]
@masterkorp take a look to promise, callback, and gulp you will understand :)

**Comment by masterkorp** [comment]
@neoziro Thank you!
