### ISSUE TITLE
Deploy with nginx in front?

### ISSUE THREAD

**Issue by arthurtalkgoal** [shipitjs/shipit#45]
Not sure if how common practice that nodejs run alone. but there is some keen discussion on it, namely ***nginx***:
https://groups.google.com/forum/?fromgroups=#!topic/nodejs/gB8veFbcX5g

Is there any support or we need not care if nginx is in front of nodejs?

**Comment by neoziro** [comment]
It's always a good practice to put nginx in front of node on your servers. But it's not relative to shipit, nginx will just forward request to node. So when you deploy your node code you just have to restart your node process.

Do you have a question relative to Shipit?

**Comment by arthurtalkgoal** [comment]
I am setting up grunt-shipit to deploy my keystonjs (on express) now.  I successfully installed grunt-shipit. but the shipit command is not found.

I am still googleing how to deploy via grunt-shipit/shipit. Thanks for your help first.

**Comment by neoziro** [comment]
@arthurtalkgoal you should use Shipit standalone version and not grunt-shipit, it's better. But if you want to use "grunt-shipit", you must use "grunt shipit:env task" to run it.
