### ISSUE TITLE
Cannot use my own port

### ISSUE THREAD

**Issue by arthurtalkgoal** [shipitjs/shipit#46]
I am using port 8888 instead of 22.

I tried to add the port in my shipitfile.js but not work:

```
  shipit.initConfig({
    default: {
      workspace: '/tmp/git',
      deployTo: '/myfolder',
      repositoryUrl: 'me@gitserver.com',
      ignores: ['.git', 'node_modules'],
      key: '/mykey',
      port: 8888,
      shallowClone: true
    },
    staging: {
      servers: 'myuser@staging.myweb.com'
    }
  });
```

**Comment by neoziro** [comment]
Use `myuser@staging.myweb.com:8888`.

**Comment by arthurtalkgoal** [comment]
Thanks @neoziro!

**Comment by timbofield** [comment]
This doesn't seem to work aye,

    live: {
            servers: 'myserver:2222',
        }


I can see shipit trying to execute the following 
`ssh deploy@myserver:2222`

When it needs to be doing
`ssh -p2222 deploy@myserver`
