### ISSUE TITLE
Add current env in shipit.config while published

### ISSUE THREAD

**Issue by tlartaud** [shipitjs/shipit#47]
Hi there,

After an environment has been published, is it possible to get the name of the current deployed environment ?
so `grunt.shipit.config('environment')` could return `staging` for example,
that could allow us to do something like the following in a "on.published" event task.
```
if(!grunt.file.exists('.env.' + grunt.shipit.config('environment')))
   // Do something
```

Thanks a lot for your appreciated work.

**Comment by neoziro** [comment]
@tlartaud try `grunt.shipit.environment`.
