### ISSUE TITLE
Dynamic server list

### ISSUE THREAD

**Issue by twalling** [shipitjs/shipit#48]
I'm having trouble figuring out a pattern which would let me fill out the server list dynamically by querying an ELB on AWS. I've added a blocking task called "config" which gets the servers, then dynamically sets `shipit.config.servers` to the new array but that value doesn't seem to carry through to the deploy tasks which run after.

Currently I'm not sure if its a limitation on the Orchestrator architecture or Shipit or that I just simply can't come up with the right pattern. If you know off hand how one might do this I think it would be a great example to document. If this use case of dynamically updating the config after calling `shipit.initConfig` isn't supported then I think it would be a wonderful feature addition.

**Comment by neoziro** [comment]
@twalling if you want to do that, you must reinitialize shipit, to do that, try to called `shipit.initialize()` after the modification of the config. I can't warranty that it will not be broken in a future update. But right now it will work.

**Comment by twalling** [comment]
Thanks, I hadn't thought to try that.
