### ISSUE TITLE
issue merging "ignores" in configurations

### ISSUE THREAD

**Issue by tinchoz49** [shipitjs/shipit#52]
Hi @neoziro, 

If you write something like: 

```
shipit.initConfig({
    default: {
      ignores: ['.git', 'node_modules'],
    },
    staging: {
       ignores: ['assets'],
    }
  })
```

The result of use _.merge to extend configurations result in:

```
ignores: ['assets', 'node_modules']
```

instead of:

```
ignores: ['.git', 'node_modules', 'assets']
```

it's overwriting the default values.

**Comment by neoziro** [comment]
@tinchoz49 yes it's the behaviour of merge in JavaScript, it's more flexible, because else you can't say "ignores nothing". The solution for you is to do a method "ignore()" that will concat + uniq your ignore and your default ignore.
