### ISSUE TITLE
Add custom command line args

### ISSUE THREAD

**Issue by menems** [shipitjs/shipit#54]
Hi,

Is There a way to add some args on command lines like:

```
shipit env task params
```
I'd like to add for example the tag/branch of a repo via  the command line and not edit the config file every time

```
shipit env deploy v1.0.1
```

May be add  -- params to stop the task list

```
shipit env [task...] -- params
```

Thanks

**Comment by masterkorp** [comment]
@menems I do this too. You can do this very simply on the shipitfile with [commander](https://www.npmjs.com/package/commander), here is a small example.

```javascript
'use strict'

let program = require('commander');

program
  .option('-r, --revision <rev>', 'Branch, commit or tag')
  .parse(process.argv);

module.exports = function (shipit) {
  require('shipit-deploy-base')(shipit);

  shipit.initConfig({
    default: {
      branch: program.revision,
      deployTo: 'path/to/deploy',
      ignores: ['.git', 'node_modules'],
      keepReleases: 20,
      repositoryUrl: 'git@github.com:myorg/myrepo',
      workspace: '/tmp/deploy/myworkspace'
    },
    staging: {
      servers: 'user@127.0.0.1'
    }
  });
};
```

Then you just run it like. 
```
shipit staging deploy -r 1.2.3

**Comment by menems** [comment]
thanks @masterkorp,

That exactly what I need, why I have not thought this solution by myself ... :)

thanks

**Comment by neoziro** [comment]
You can also use [node-optimist](https://github.com/substack/node-optimist) it's very light.
