### ISSUE TITLE
Problems with interactive SSH

### ISSUE THREAD

**Issue by chrrasmussen** [shipitjs/shipit#56]
Hi! I really want to use this library, but I am having problems with remote commands that require user input.

I have the following `shipitfile.js` (`ShipIt-InteractiveSSHTest` is a private repository to force a login inquiry):

``` javascript
module.exports = function (shipit) {
  shipit.initConfig({
    staging: {
      servers: 'root@example.com'
    }
  });
  shipit.task('test', function () {
    return shipit.remote('git clone https://github.com/chrrasmussen/ShipIt-InteractiveSSHTest.git'); // Command #1
    // return shipit.remote('read test; echo $test'); // Command #2
  });
};
```

When I run `shipit staging test` I am getting the following output:

``` shell
$ shipit staging test

Running 'test' task...
Running "git clone https://github.com/chrrasmussen/ShipIt-InteractiveSSHTest.git" on host "example.com".
@example.com-err Cloning into 'ShipIt-InteractiveSSHTest'...
@example.com-err fatal: could not read Username for 'https://github.com': No such device or address
'test' errored after 1.91 s
Error: Command failed: /bin/sh -c ssh root@example.com "git clone https://github.com/chrrasmussen/ShipIt-InteractiveSSHTest.git"
Cloning into 'ShipIt-InteractiveSSHTest'...
fatal: could not read Username for 'https://github.com': No such device or address

    at ChildProcess.exithandler (child_process.js:685:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:953:16)
    at Socket.<anonymous> (child_process.js:1118:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe._onclose (net.js:453:12)
Unhandled rejection Error: Command failed: /bin/sh -c ssh root@example.com "git clone https://github.com/chrrasmussen/ShipIt-InteractiveSSHTest.git"
Cloning into 'ShipIt-InteractiveSSHTest'...
fatal: could not read Username for 'https://github.com': No such device or address

    at ChildProcess.exithandler (child_process.js:685:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:953:16)
    at Socket.<anonymous> (child_process.js:1118:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe._onclose (net.js:453:12)
```

Unfortunately, the script does not give me a chance to input my username and password.

The `shipitfile.js` contains another command as well (which is commented out). When I run the script including this line I am able to enter som input, but when I press return it gives me a newline instead of continuing to the next command (`echo $test`).

Should these remote commands work like I expect? And if so, what am I doing wrong?

I am running Mac OS X 10.10.3, IO.js v1.7.1 (I also tried the system-supplied version of Node.js, v0.10.26), OpenSSH_6.2p2 OSSLShim 0.9.8r 8 Dec 2011. Please let me know if you need any other information.

I am sorry if this is not the correct place to ask for help. In that case, feel free to close and delete this issue.

**Comment by masterkorp** [comment]
@chrrasmussen Normally on deploys you want it to be a non interactive operation.

The git clone problem should be easily fixable by cloning using SSH method (not https) and having a deploy key on the servers.

If you deploy to many servers, an interactive process will quickly become a pain.

**Comment by chrrasmussen** [comment]
@masterkorp Thanks for your answer! You are probably right that I should avoid interactive operations in the deployment.

However, what I want to achieve is to run some scripts on the remote server (after deployment) that may prompt me for input, without manually SSH-ing into the remove server. Based on Shipit's readme ("Login and interactive SSH commands") it sounds like this should be possible, leading me to believe that I am doing something wrong.

**Comment by neoziro** [comment]
Relative to #12

**Comment by krns** [comment]
Hi,

how is it possible to execute ship it commands in a login shell? I'm executing a shipit.remote()-command but the execution shell is not a login shell. 

Like @chrrasmussen I have also read about the feature
> Login and interactive SSH commands

in the readme. I haven't found a solution in the referenced issues.

**Comment by neoziro** [comment]
@krns Shipit runs only sudo command in a login shell.. It's a feature on the list to be able to run another command without sudo https://github.com/shipitjs/shipit/issues/12, it needs some dev in ssh-pool module and it's pretty easy to do but right now I don't have time to do it.

**Comment by neoziro** [comment]
https://github.com/shipitjs/ssh-pool/pull/26 will solve the problem

**Comment by neoziro** [comment]
Will be fixed in v4.
