### ISSUE TITLE
shipit.local tasks unexpectedly failing

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#57]
I'm using Gulp, and starting my `shipit-deploy` task in a `gulp deploy` task.

Simplified, it looks something like this:
```
    shipit = new Shipit({environment: deployToEnv});
    require(path.join(process.cwd(), 'shipitfile.js'))(shipit);
    shipit.initialize();
    shipit.start('deploy');
```

Everything works fine when I run `gulp deploy` except one crucial thing:

With this in my shipitfile, I need it to run `npm install`, then `gulp build` on `fetched`
```
  shipit.blTask('build', function() {
    return shipit.local('npm install', {
      cwd: shipit.config.workspace
    }).then(function() {
      return shipit.local('gulp build', {
        cwd: shipit.config.workspace
      });
    });
  });

  shipit.on('fetched', function() {
    shipit.start('build');
  });
```

However, here's what happens:
```
Finished 'deploy:fetch' after 3.23 s

Running 'build' task...
Running "npm install" on local.
Running "gulp build" on local.
@ [13:59:48] Local gulp not found in /private/tmp/edwards-garment-website
@ [13:59:48] Try running: npm install gulp
'build' errored after 556 ms
Error: Command failed:
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
Unhandled rejection Error: Command failed:
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

As you can see, it doesn't actually install anything with the `npm install`, and therefore breaks the `gulp build`.

However with the same config, `shipit development deploy` works fine.

Any ideas?

**Comment by neoziro** [comment]
@timkelty no idea sorry, try to debug to see the exact command that is sent.

**Comment by timkelty** [comment]
Ok, I dug in a bit more. It seems it is not actually just isolated to Gulp.

I found a particular dependency that is causing this, which is throwing a deprecation warning (`jQuery` vs `jquery` as a dep). If I manually `npm install`, I get a warning, but it successfully installs. If `shipit.local` runs `npm install`, it dies.

# via `shipit develoment deploy`

```
npm ERR! version not found: jQuery@1.7.4
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/edwards-garment-website/npm-debug.log

    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:117:20)
    at Pipe.close (net.js:465:12)
```

# via `npm install` on the CLI

```
npm WARN deprecated jQuery@1.7.4: This is deprecated. Please use 'jquery' (all lowercase).
...
responsive-tabs@1.4.4 node_modules/responsive-tabs
└── jQuery@1.7.4
```

**Comment by timkelty** [comment]
Another example:
After fixing the issue above, it now dies here:
```
Unhandled rejection Error: Command failed: npm WARN engine slack-notify@0.1.4: wanted: {"node":"0.10.x","npm":"1.3.x"} (current: {"node":"0.10.33","npm":"2.1.5"})
npm WARN engine jquery@1.7.2: wanted: {"node":"0.6"} (current: {"node":"0.10.33","npm":"2.1.5"})
```

via 'npm install` (manually)
```npm WARN engine slack-notify@0.1.4: wanted: {"node":"0.10.x","npm":"1.3.x"} (current: {"node":"0.10.33","npm":"2.1.5"})``` and it just continues along...

**Comment by timkelty** [comment]
Some success: adding the `--silent` argument to `npm install` fixes `shipit development deploy`.

However, when trying to initialize and run shipit through gulp, it doesn't install any modules and tries to go right into `gulp build`

**Comment by timkelty** [comment]
Made a SE post: http://stackoverflow.com/questions/29988714/child-process-exec-prematurely-resolving-with-npm-install-command-via-gulp-sh

**Comment by timkelty** [comment]
I discovered that if I change the `shipit.local` command to `sudo npm install`, it works. That give you any ideas?

**Comment by neoziro** [comment]
@timkelty probably a problem with "interactive mode" of ssh? Because actually in sudo mode, it's interactive. I plan to change it in the next version.

**Comment by neoziro** [comment]
Relative to #12

**Comment by timkelty** [comment]
I forgot to mention - I figured this out and it wasn't really related to `sudo` or Shipit after all.

The problem was that I was that my `NODE_ENV` was set to `production`, and therefore when I had `shipit.local` run `npm install`, `devDependencies` did not install. I fixed this by running `shipit.local('NODE_ENV=development npm install')` instead.
