### ISSUE TITLE
DO NOT DO "rm -rf" WITHOUT USERS CONFIRMATION!

### ISSUE THREAD

**Issue by scaryguy** [shipitjs/shipit#61]
Currently, I'm pretty angry. I've been using open source projects more than 10 years but it's the first time I'm experiencing such a thing... 

I was just about the give a try to your Shipit project to deploy my node.js app. Started to set up the `shipitfile.js`.

>workspace
>Type: String
>Define the local working path of the project deployed.

As it's stated at the README file(!) I entered full path to my project directory to `workspace` field. What am I (or anyone) is supposed to understand from this sentence?

And than I typed `shipit staging deploy` and hit the enter button...

EVERY SINGLE FILE IN MY REPOSITORY WAS DELETED by your module. With a **friendly** message telling `Deleting existing files`... God!..

Thankfully, I had a remote copy of the repository BUT I have lost ALL of my working tree!..

Even though I wouldn't lose anything, I'm here to tell you: 
### Please DO NOT DO "rm -rf" WITHOUT USERS' CONFIRMATION! 

People are trusting you and using your software. Deleting any user file without confirmation.... Come on man!

**Comment by thelinuxlich** [comment]
I agree that workspace is very, very misleading...should be something like temporary_build_dir

**Comment by masterkorp** [comment]
:+1:

**Comment by neoziro** [comment]
@scaryguy I agree that it's confusing, sorry for your problem, I would try to be more explicit in the next version

**Comment by neoziro** [comment]
@scaryguy it's an issue for shipit-deploy, not shipit. So I close it and reopen it in the other repo.
