### ISSUE TITLE
Could do with better documentation

### ISSUE THREAD

**Issue by bgSosh** [shipitjs/shipit#63]
Hi, 

This project looks very interesting, but it could really do with more detailed documentation, and some examples etc. (I can't find a single example shipitfile.js on the web).  It's not entirely clear to me what the scope of the project is, what exactly it adds on top of Orchestrator, what features are shipit and what the shipit-deploy plugin etc.. (I had a look at the shipit source, and was a bit confused to see references to 'keepReleases' and 'shallowClone' which I thought would be part of shipit-deploy).  

Cheers

**Comment by neoziro** [comment]
@bgSosh yes I agree

**Comment by neoziro** [comment]
The documentation is cheap especially for shipit-deploy, any contributions are welcome.

**Comment by jdat82** [comment]
Yeah, documentation is a bit light, notably for shipit-deploy. An explanation of some variable purpose would be great like shallowClone, plus in option, an example when useful. 

Concerning the `servers` option, it is said it can be either a `String` or an `Array<String>` but in the sample under, it is an `Array<Object>` which notation is not documented. Is there a third notation ?

**Comment by neoziro** [comment]
@jdat82 not only the ones you listed

**Comment by neoziro** [comment]
Documentation will be improved in v4, released at the end of the month.
