### ISSUE TITLE
shipit.remote('sudo whoami') - command executed BUT connection error.

### ISSUE THREAD

**Issue by iMoses** [shipitjs/shipit#64]
Whenever I try to use `sudo` as part of my `shipit.remote` command the following error occurs and the connection is lost, causing some commands on the remote host not to execute while other does.

```
        return shipit.remote('sudo whoami')
            .then(function () {
                shipit.log('Services restarted.');
                done(); //grunt async callback
            });
```

Will result in the following log:

```
Running "shipit-test" task
Restarting services
Running "sudo whoami" on host "dev.mysite.com".
@dev.mysite.com root
@dev.mysite.com-err Connection to dev.mysite.com closed.
Services restarted.
```

When I use `whoami` at least I get a result, but when trying to use `sudo service __name__ restart` the service will stop and never start again. That's a problem.

I've located the problem and it directly related to the use of pseudo-tty. I agree that in most cases this can be a good thing, but there must be an option to disable automatic tty when needed. Currently my trick is to put a space before the `sudo` command to confuse the regex matching.
Please add an option to disable this feature.

**Comment by neoziro** [comment]
@iMoses yes there is an issue about this #12
