### ISSUE TITLE
Why does shipit.start() not return a promise?

### ISSUE THREAD

**Issue by bgSosh** [shipitjs/shipit#65]
I've just started using shipit, but I'm surprised that start(task) does not return a promise (perhaps I'm missing something).  And far as I can see there's not really any way of getting start([tasks]) to complete tasks in sequence - it seems that if you want to run them in order then the tasks themselves need to know about the other tasks that will be run, which seems to defeat the purpose of them being separate tasks.

Is the callback in start(tasks, callback) the only way to run tasks in a certain order?

Ie.

    shipit.task('one', function () {
        return shipit.local('someCommand');
    });

    shipit.task('two', function () {
        return shipit.local('someCommand');
    });

    shipit.task('doAll', function() {
       //How to use shipit.start() to execute tasks one and two in sequence?
    });

**Comment by vlkosinov** [comment]
You are right. Start does not return promise, but it's depends on orchestrator, not on shipit.

**Comment by neoziro** [comment]
@vlkosinov +1
