### ISSUE TITLE
Event not firing?

### ISSUE THREAD

**Issue by davejacobs** [shipitjs/shipit#71]
I have the following shipitfile.js and have successfully deployed to production using shipit-deploy. However, I'm not seeing events firing. In particular, I don't see the shipit log message and don't the the appropriate files copied over.

What am I doing wrong?

shipitfile.js:

```javascript
module.exports = function(shipit) {
  require("shipit-deploy")(shipit);

  shipit.initConfig({
    default: {
      repositoryUrl: "<the repo>",
      branch: "master",
      ignores: [".git", "node_modules"],
      workspace: "/tmp/<the workspace>",
      deployTo: "www/<the deploy dir>",
      keepReleases: 3,
      key: "<the SSH key>",
    },
    production: {
      // ...
    }
  });

  // Copy over secrets before we deploy to servers.
  shipit.task("copy:secrets", function() {
    return shipit.local("gulp copy:secrets-to-workspace");
  });

  shipit.on("deploy:fetch", function() {
    shipit.log("Copying secrets.");
    shipit.start("copy:secrets");
  });
};
```

**Comment by neoziro** [comment]
@davejacobs it's not the correct name of the event, please refer to [Workflow tasks section](https://github.com/shipitjs/shipit-deploy#workflow-tasks) to see what event to use (in your case "fetched").

**Comment by davejacobs** [comment]
I see, thanks!
