### ISSUE TITLE
Extend shipit cli util

### ISSUE THREAD

**Issue by halfdan** [shipitjs/shipit#75]
The command line could be extended with some simple utility functions:
- [ ] `--init` option that generates a stub shipitfile.js
- [x] `--help` option (self-explanatory)
- [ ] `--plugin` or `--init-plugin`, generates empty shipit extension in a folder `shipit-$name`, runs `npm install` to install some default dependencies

Feedback/Suggestions? I'd be happy to work on those three.

**Comment by cognitom** [comment]
:+1: 
How about these, too?

- [ ] `--tasks` option that shows registered tasks
- [ ] `--environments` option that shows registered environments

**Comment by halfdan** [comment]
@cognitom Great idea. Working on implementing them.

**Comment by timkelty** [comment]
@halfdan @cognitom -
I just published https://github.com/timkelty/shipit-captain for an easy way to extend the CLI, or replace it with your favorite task runner.

**Comment by neoziro** [comment]
Idea for the v4.

**Comment by neoziro** [comment]
Done except generators. I will open a new issue.
