### ISSUE TITLE
Proposal: Recipe directory

### ISSUE THREAD

**Issue by cognitom** [shipitjs/shipit#81]
How about making the recipe directory like gulp? I can send some PR.
https://github.com/gulpjs/gulp/tree/master/docs/recipes

It helped me so much when I learned gulp.

**Comment by timkelty** [comment]
That sounds like a great idea!

**Comment by neoziro** [comment]
Great idea, feel free to make a PR!

**Comment by neoziro** [comment]
Idea for v4.
