### ISSUE TITLE
rsync options are not forwarded.

### ISSUE THREAD

**Issue by mochja** [shipitjs/shipit#83]
I did originally create pull request [here](https://github.com/shipitjs/shipit-deploy/pull/76), but source of problem is somewhere else.

You're [passing](https://github.com/shipitjs/shipit-deploy/blob/master/tasks/deploy/update.js#L70) configuration object as `{rsync: '--del'}` whis is then [resolved as default value](https://github.com/shipitjs/shipit/blob/master/lib/shipit.js#L243) and based on [lodash documentation](https://lodash.com/docs#defaults) of `defaults`

> Assigns own enumerable properties of source object(s) to the destination object for all destination properties that resolve to undefined. **Once a property is set, additional values of the same property are ignored.**

is [this line](https://github.com/shipitjs/shipit/blob/master/lib/shipit.js#L245) currently never evaluated, also tests for this specific real case are not written.

**Comment by neoziro** [comment]
I don't understand, you want rsync options to be merged? If this is the case, it will not be done, because each options of Shipit are replaced and not merged, si it's intended.

**Comment by mochja** [comment]
solved by ff01ebe7df16592b87477b050e27c2aafbb0a289
