### ISSUE TITLE
Multiple entries for dirToCopy

### ISSUE THREAD

**Issue by LoganBarnett** [shipitjs/shipit#85]
Apologies if this is in the wrong project (vs `shipit-deploy`).

My project uses both a client UI (served as a bunch of static files) and a server app.

What I'd like to do is roll them both out more or less atomically using shipit. I need my static files to live in some place where the web server can get to them, but I'm not keen on having the web server also potentially serving up the server code.

A possible approach might be instead of `dirToCopy` and `deployTo`, what if there was just a `copy` or `deploy` that takes a list of objects with something akin to `from` and `to` properties?

I'm not committed to that approach - maybe there's a preferred way to do this already? I don't mind putting together a PR if one is needed but I figured discussion would be better to start with :)

**Comment by travco** [comment]
@LoganBarnett Sorry that nobody got you in a timely manner. 

 - Yes, this is the wrong repo for this issue, it would indeed be shipit-deploy for proposing dirToCopy and deployTo alternatives.
 - This seems like something that can be worked out with your webserver config. If your really worried about it serving up server code, you should just take the time to verify your settings. If you have a configuration where your not sure which of the files your webserver can read are being served up, then by nature of the problem - there is no guaranteeing what your server is reading in isn't being served regardless of location. A more specific deploy operation isn't going to help.
 - The repos like shipit-deploy are there to give you premade general-use tasks for shipit (this repo). Wanting to do a task like what you are suggesting is a little more niche, and it something you can always just configure yourself. Infact, the tasks in shipit-deploy are excellent reference, and probably only need to be modified slightly.

**Comment by LoganBarnett** [comment]
Thanks! That all makes sense. I'll close the ticket up.
