### ISSUE TITLE
using shipit with a CI

### ISSUE THREAD

**Issue by callerc1** [shipitjs/shipit#86]
Hi Guys,

Im having issues when a shipit task fails but no exit code is given. What this means is the CI tool assumes success even tho clearly the task has failed. Essentially we need an exit code of anything but 0 to catch failures in the CI tool.

**Comment by bdossantos** [comment]
+1

**Comment by loliee** [comment]
+1

**Comment by ianwremmel** [comment]
Running into the same problem; would love to see #87 get merged.

**Comment by devster** [comment]
:+1:
