### ISSUE TITLE
How to make remoteCopy execute with sudo

### ISSUE THREAD

**Issue by johnmcdowall** [shipitjs/shipit#89]
Is it possible to make remoteCopy execute with `sudo` or as `root`?

**Comment by johnmcdowall** [comment]
Ah, turns out I was able to pass:

`grunt.shipit.remoteCopy( <file>, <file>, { rsync: '--rsync-path="sudo rsync"' })`

Would you accept a PR adding a `remoteCopySudo` method, as it seems like this would be a common task to me?

**Comment by neoziro** [comment]
@johnmcdowall if it works like it I think we don't need a remoteCopySudo command. I think you should not use sudo one your remote server, you can achieve it with a custom "deploy" user with good rights.
