### ISSUE TITLE
Add cwd option in remote command

### ISSUE THREAD

**Issue by neoziro** [shipitjs/shipit#9]
To avoid "cd .." before running command.

**Comment by thelinuxlich** [comment]
shipit.remote doesn't accept cwd option?

**Comment by neoziro** [comment]
@thelinuxlich yes but this is the local cwd directory, not the remote one.

**Comment by thelinuxlich** [comment]
does it make sense this behavior in shipit.remote?

**Comment by neoziro** [comment]
@thelinuxlich I think not, do you think it's more clear to have "cwd" for local and remote instead of "cwd" and "remoteCwd"?

**Comment by thelinuxlich** [comment]
Yes, I think it would be more intuitive if cwd worked as expected on shipit.remote

**Comment by vlkosinov** [comment]
It's really useful option for remote.

**Comment by IcanDivideBy0** [comment]
+1

**Comment by Sija** [comment]
+1

**Comment by ngryman** [comment]
:+1:

**Comment by sjelfull** [comment]
Related(?): From the docs, I assumed the "workspace" option would automatically cwd to that folder on remote.

**Comment by vinayr** [comment]
+1

**Comment by albertogasparin** [comment]
+1 as current `cwd` behaviour is misleading

**Comment by tim-field** [comment]
So is this the way you are meant to do this ?

```
    shipit.blTask('yarn:install', function () {
      return shipit.remote('cd '+shipit.releasePath+'; yarn install')
    })
```

How much time is being collectively wasted here as everyone trys to work out why cwd isn't working! ;)

**Comment by timkelty** [comment]
@tim-field unfortunately yes.

> How much time is being collectively wasted here as everyone trys to work out why cwd isn't working! ;)

Too much. Happy for someone to make a PR, otherwise I'll get to it when I can.

**Comment by timkelty** [comment]
Merged in with `3.0.0`

**Comment by neoziro** [comment]
Will be done soon https://github.com/shipitjs/ssh-pool/pull/26

**Comment by neoziro** [comment]
Will be part of v4.
