### ISSUE TITLE
Consider config/environment changes (2.0)

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#93]
Currently all options from `default` and your target env are merged together.

However, it may be desirable to maintain separate settings between your local environment and a remote server.

For example, `shipit-db`, which syncs mysql db between local and remote. To achieve this currently, I have options like `shipit.config.db.remote` and `shipit.config.db.local`. E.g. https://github.com/timkelty/shipit-db#example-shipitfilejs

It works, but seems less than ideal for each plugin to have to do that.

How about if we merge everything as we do now, but keep the other environments' still accessible via `shipit.config.environments` or something?

Seems the most flexible without breaking anything. Open to any other ideas.

**Comment by neoziro** [comment]
I don't understand what do you mean by merging.

**Comment by timkelty** [comment]
Currently, a Shipit, `shipit`, has a `shipit.config` property which is the result of the your environemnet config, merged with your `default` config.

**Comment by neoziro** [comment]
@timkelty ok and you just want to keep an access to the original environments config, yes it's OK for me.

**Comment by timkelty** [comment]
@neoziro Right. I'll work on a PR
