### ISSUE TITLE
emit start/stop events

### ISSUE THREAD

**Issue by timkelty** [shipitjs/shipit#94]
It would be helpful for shipit to emit global shipitStart, shipitStop events, if you want to trigger something before/after ANY Shipit tasks.

You can do this with [shipit.on('start')](https://github.com/orchestrator/orchestrator#event), but I think it should be more specific. It also seems to frequently "Maximum call stack size exceeded" when doing it this way.

**Comment by neoziro** [comment]
@timkelty hmm why not, but yes redundant with orchestrator...
