### ISSUE TITLE
exit process on error - tag timeline?

### ISSUE THREAD

**Issue by blackdynamo** [shipitjs/shipit#99]
Hey, was just wondering when you plan on pushing out the latest change from July that actually exits the process on task_err.

https://github.com/shipitjs/shipit/commit/e99fe2da270aecd548e5c18b1ba8a4023ba703d3

Thanks in advance :)

**Comment by travco** [comment]
@blackdynamo, e99fe2d should have been pushed out in v1.4.1

I'm sure the team appreciated the heads up :)
Do you mind closing the issue?

**Comment by blackdynamo** [comment]
Thanks 👍
